== The Life of Thomas Ellwood

Although my station--being not so eminent either in the church of Christ or in the world,
as others who have moved in higher spheres--may not
afford such noteworthy remarks as theirs;
yet, inasmuch as in the course of my travels through this valley of tears,
I have passed through various, and some uncommon exercises,
which the Lord has been graciously pleased to support me under and conduct me through;
I hold it a matter excusable at least, if not commendable,
to give the world some little account of my life.
In recounting the many deliverances and preservations
which the Lord has graciously worked for me,
my desire on the one hand is to return grateful acknowledgment
and thanksgiving unto Him for His abundant goodness to me.
And on the other hand, if there be any who happen to tread the same path,
and fall into the same or similar exercises,
my hope is that these may be encouraged to persevere in the way of holiness,
and with full assurance of mind to trust in the Lord, whatever trials may befall them.

I begin, therefore, with my own beginning.
I was born in the year of our Lord 1639, about the beginning of the eighth month,
so far as I have been able to inform myself; for the parish register,
which relates to the time, not of birth,
but rather of baptism (as they call it) is not to be relied on.

The place of my birth was a little country town called Crowell,
situated in the upper side of Oxfordshire, three miles eastward from Thame,
the nearest market-town.
My father`'s name was Walter Ellwood; and my mother`'s maiden name was Elizabeth Potman;
both well-descended, but of declining families.
What my father possessed, which was a sizable estate in lands,
and more (as I have heard) in money, he received, as he had done his name Walter,
from his grandfather Walter Gray, whose daughter and only child was his mother.

In my very infancy, when I was but about two years old, I was carried to London.
For as the civil war between king and parliament was breaking forth at that time,
my father, who favored the parliament side (though he took up no arms),
not believing himself safe at his country habitation
which lay near some of the king`'s garrisons,
removed to London, that city then holding for the parliament.

There I was raised, though not without much difficulty,
for the city air did not agree with my tender constitution.
And there I continued until Oxford was surrendered, and the war in appearance had ended.

During this time,
my parents contracted an acquaintance and intimate friendship with the lady Springett,
then the widow of Sir William Springett, who died in the parliament service,
and who afterwards was the wife of Isaac Penington,
eldest son of alderman Penington of London.
This friendship devolving from the parents to the children,
I became an early and particular playfellow to her daughter Gulielma;
being permitted to ride with her in her little coach,
drawn by her footman around Lincoln`'s-Inn-Fields.
I mention this in this place,
because the continuation of this friendship was the means of my
afterwards being brought to the knowledge of the blessed Truth,
and I shall have frequent cause in the following
pages to make honorable mention of that family,
to which I am under many and great obligations.

Soon after the surrender of Oxford, my father returned to his estate at Crowell;
which by that time he had need enough to attend to, having spent, I suppose,
the greatest part of the money which had been left to him by his grandfather
in maintaining himself and his family at a high rate in London.
My elder brother--for I had one brother and two sisters
all older than myself--while we lived in London,
was boarded at a private school, in the house of one Francis Atkinson,
at a place called Hadley, near Barnet in Hertfordshire,
where he made some good proficiency in the Latin and French tongues.
But after we left the city, and were resettled in the country,
he was taken from that private school,
and sent to the free school at Thame in Oxfordshire.
There also I was sent, as soon as my tender age would permit;
for I was indeed but young when I went,
and seemed even younger than I was by reason of my low and little stature.
It was considered for some years a point of question whether I would prove to be a dwarf.
But after I arrived to the fifteenth year of my age, or thereabouts, I began to shoot up,
and did not stop growing till I had attained about the average size and stature of men.

At this school, which at that time was in good reputation, I profited quickly,
having then a natural propensity to learning;
so that after the first reading over of my lesson,
I commonly felt myself to have mastered it.
And yet, which is strange to think of,
few boys in the school wore out the teacher`'s switch
more than I. For though I was never,
that I remember, whipped upon the account of not having my lesson ready,
or of not saying it well; yet being a little busy-body, full of spirit,
with a working head and an active hand,
I could not easily conform myself to the grave and sober rules of the school,
which I then thought were severe.
I was often playing one humorous prank or other on my fellow-students,
which subjected me to correction,
so that I have come under the discipline of the rod twice in a morning,
though I never broke any bones.

Had I continued at this school, and in due time continued to a higher,
I might in likelihood have become a scholar;
for I was said to have had a genius aptitude to learn.
But as soon as the republican government began to settle,
my father accepted the office of a justice of the peace, which was in no way beneficial.
This new position was merely honorary and in every way expensive,
and so put him into a course of living that was agreeable thereto.
And as he had also removed my brother from Thame school to Merton college in Oxford,
and entered him there in the highest and most expensive position,
he found it needful to reduce his expenses elsewhere; the hurt of which fell upon me.
For he thereupon took me out of school to save the charge of maintaining me there;
which was somewhat like plucking green fruit from the tree,
and laying it aside before it had come to its due ripeness,
which will then shrink and wither,
and lose that little juice and relish which it began to have.

This is how it fared with me.
For being taken home when I was but young,
and before I was well settled in my studies--though
I had made a good progress in the Latin tongue,
and had entered into the Greek--and being left too much to myself to do as I pleased,
I soon shook hands with my books,
by shaking my books out of my hands and laying them quite aside,
and addicted myself to such youthful sports and pleasures as the place afforded,
and my condition could reach for.

By this means I soon began to lose the little learning I had acquired at school;
and by a continued disuse of my books,
I became at length so utterly a stranger to learning, that I could not have read,
far less have understood, a sentence in Latin.
Indeed, I was so sensible of this, that I carefully avoided reading to others,
even in an English book, lest if I should meet with a Latin word,
I would embarrass myself by mispronouncing it.

Thus I went on, taking my swing in such vanities as were accounted harmless recreations;
entertaining my companions and familiar acquaintances
with pleasant discourses in our conversations.
This I did by the mere force of wit and natural abilities,
without the help of school cultivation; and I was accounted good company too.

But I always surrounded myself with persons of ingenuity, temperance and sobriety;
for I loathed obscenity in conversation,
and had a natural aversion to immoderate drinking.
So that in the time of my greatest vanity,
I was preserved from profaneness and the grosser evils of the world;
which rendered me acceptable to persons of the highest regard in that country.
I often visited Lord Thomas Wenman^
footnote:[Lord Thomas Wenman,
was an English landowner and politician who sat in the House
of Commons at various times between 1621 and 1660.]
at his house at Thame-park, about two miles from Crowell where I lived;
to whose favor I was entitled in a two-fold respect,
both because my mother was nearly related to his wife,
and because he had been pleased to bestow his name upon
me when he made large promises for me at my baptism.
He was a person of great honor and virtue,
and always gave me a kind reception at his table, however often I came.
And I have reason to believe I would have received from
this lord some advantageous preferments in this world,
as soon as he had found me capable of it, had I not been, in a little time after this,
called into the service of the best and highest Lord;
and thereby lost the favor of all my friends, relations and acquaintance of this world.
I hasten to the relation of this most happy change,
and therefore willingly pass over many particularities of my youthful life.
Yet one occurrence I am willing to mention,
because of the effect it had upon me afterwards, which was as follows.

My father, being then in commission as a justice of the peace,
and going to a court session at Watlington, I accompanied him there.
And when we came near the town,
the coachman seeing a nearer and easier way than the common road, through a corn-field,
and that it was wide enough for the wheels of the
coach to run upon without damaging the corn,
turned that way.
This being observed by a husbandman who was plowing not far off, he ran to us and,
stopping the coach,
poured forth a mouthful of complaints in rather unhandsome
language for driving over the corn.
My father mildly answered him, that if there was an offense committed,
he must rather impute it to his servant than himself;
since he neither directed him to drive that way, nor knew which way he drove.
Yet he added that, as he was going to such and such an inn at the town,
if the man would come there,
he would make him full satisfaction for whatsoever damage he had sustained.
And so we went on, as the man continued to vent his discontent in angry tones.
At the town, upon inquiry,
we understood that it was indeed a way often used by travelers, and without any damage,
being broad enough; but that it was not the common road, which yet lay not far from it,
and was also good enough.
My father therefore bid his servant to drive home on the common road.

It was late in the evening when we returned, and very dark; and this quarrelsome man,
who had troubled himself and us in the morning,
having gotten another stout fellow like himself to assist him, waylaid us in the night,
expecting that we would return the same way we had come.
But when they found that we did not, but took the common way,
being angry that they were disappointed, and unwilling to lose their purpose,
which was to abuse us, they hurried over to us in the dark,
and laying hold upon our horses`' bridles, stopped them from going on.
My father asked his servant the reason why he did not continue on,
and was answered that there were two men at the head of the horses who held them back,
and would not permit them to go forward.
My father therefore opened the coach and stepped out, and I followed close at his heels.
Going up to where the men stood, he demanded of them the reason for this assault.
They said we were driving upon their corn.
But we knew that we were not on the corn, but in the common road, and so told them so.
But they told us they were resolved not to let us go on any farther,
but would make us go back again.
My father endeavored, by gentle reasoning, to persuade them to forbear,
and not to run themselves farther into the danger of the law,
which they had run too far into already; but they only derided him for it.
Seeing therefore that fair means would not work upon them, he spoke more roughly to them,
demanding them to deliver over their clubs,
for each of them had a great club in his hand.
Laughing, they told him they did not bring them there for that purpose.
Thereupon my father, turning his head to me, said, "`Tom, disarm them.`"

I stood ready at his elbow, waiting only for the word of command.
For being naturally of a bold spirit, and full of youthful passion,
and that now heightened by the sense I had, not only of the abuse,
but the insolent behavior of those rude fellows--my
blood began to boil and my fingers itched,
as the saying goes, to deal with them.
I therefore stepped boldly forward to lay hold of
the staff of the one that was nearest to me,
and said, "`Sirrah, deliver your weapon.`"
He thereupon raised his club, which was big enough to have knocked down an ox,
intending no doubt to have knocked me down with it, as probably he would have done,
had I not, in the twinkling of an eye, whipped out my sword and made a pass upon him.
I could not have missed running him through to the hilt had he stood his ground;
but the sudden and unexpected sight of my bright blade glittering in the dark night,
did so amaze and terrify the man, that slipping aside, he avoided my thrust.
Then letting his staff fall to the ground, he took to his heels for safety,
which his companion seeing, fled also.
I followed the former as fast as I could, but fear gave him wings,
and made him fly swiftly.
And though I was accounted very nimble,
yet the farther we ran the more ground he gained on me, and I could not overtake him;
which made me think he took shelter under some bush which he knew where to find,
though I did not.
Meanwhile the coachman excused himself from intermeddling,
under pretense that he dared not leave his horses, and so left me to fend for myself.
I had run so far, that I knew not which way to go to return, until by hollering,
and being hollered to in return, I was directed where to find my company.

We had an easy means of finding out who these men were,
for the principal of them had been at the inn in
the daytime and quarreled with the coachman,
threatening to get even with him when he went back.
But since they had gained nothing by their attempt,
my father thought it better not to know who they were,
than to oblige himself to a prosecution.

At that time, and for a good while after,
I had no regret upon my mind for what I had done,
or for what I would have done in this case; but went on, in a sort of bravery,
resolving to kill any man that would make a similar attempt, or put any affront upon us.
And for this reason,
I seldom went afterwards upon any such excursions without a loaded pistol in my pocket.
But when it pleased the Lord, in His infinite goodness,
to call me out of the spirit and ways of the world,
and give me the knowledge of His saving Truth,
whereby the actions of my past life were set in order before me--then,
a sort of horror seized upon me,
when I considered how near I had been to staining my hands with human blood.
And whensoever afterwards I passed that way,
and indeed as often as the matter has come into my remembrance,
my soul has blessed the Lord for my deliverance,
and thanksgivings and praises have arisen in my heart (as now they do at the
relating of it) to Him who preserved and withheld me from shedding man`'s blood.
This is the reason I have given this account of that action,
that others may be warned by it.

About this time, in the year 1658, my dear and honored mother,
who was indeed a woman of remarkable worth and virtue, departed this life,
having a little before heard of the death of her eldest son.

I mentioned before, that during my father`'s abode in London,
in the time of the civil wars, he contracted a friendship with the lady Springett,
then a widow, who afterwards was married to Isaac Penington;
and in order to continue this relationship,
he sometimes visited them at their country lodgings near Reading.
Having heard that they had come to live upon their own estate at Chalfont in Buckinghamshire,
about fifteen miles from Crowell, he went one day to visit them there,
and to return at night, taking me along with him.
But we were very much surprised when, having come there, we first heard, and then found,
that they had become Quakers--a people we had no knowledge of,
and a name we had till then scarcely heard of.
Finding so great a change from the free,
debonair and cultured sort of behavior which we formerly found them in,
to so strict a gravity with which they now received us,
we were both amused and disappointed of our expectation of having
such a pleasant visit with them as we used to have.
And as there were some other strangers with them,
relatives of Isaac Penington who had come that morning from London to visit them,
my father had no opportunity, by a private conference with them,
of understanding the ground or occasion of this change.

For my part,
I sought and eventually found means to cast myself into the company of their daughter,
Gulielma,^
footnote:[Some years after this, Gulielma became the wife of William Penn.]
whom I found gathering some flowers in the garden, attended by her maid,
who was also a Quaker.
But when I addressed myself to her after my accustomed manner,
with intention to engage her in some discourse based upon our former acquaintance,
though she treated me with a courteous demeanor, yet, as young as she was,
the gravity of her look and behavior struck such an awe upon me,
that I found myself not so much master of myself
as to pursue any further conversation with her.
Therefore,
asking pardon for my boldness in having intruded myself into her private walks,
I withdrew, but not without some disorder of mind.

We stayed for dinner, which was very pleasant and lacked nothing to recommend it to me,
besides the lack of mirth and pleasant discourse which we could neither have with them,
nor, by reason of them, have amongst ourselves.
For the weightiness that was upon their spirits and countenances
kept down the lightness that would have risen up in us.

We nevertheless stayed until the rest of the company had taken leave of them,
and then we also returned home, not greatly satisfied with our journey,
but not knowing what in particular to find fault with.
Yet this visit had one good effect upon my father, who was then a justice of the peace,
for it disposed him to a more favorable opinion of,
and behavior towards this people when they came in his way;
as one of them did not long after this.
For a young man who lived in Buckinghamshire,
came on a first-day to the church (so called) at a town called Chinner,
a mile from Crowell, having, it seems,
a burden on his mind to say something to the minister of that parish.
This minister, being an acquaintance of mine, invited me sometimes to hear him,
as it happened that day.
The young man stood in the isle before the pulpit, all the time of the sermon,
not speaking a word until the sermon, and the prayer after it, had ended.
He then spoke a few words to the priest, of which, all that I could hear was,
that "`the prayer of the wicked is an abomination to the
Lord;`" and "`that God hears not sinners.`"

I believe there was something else said which I could
not distinctly hear because of the noise of the people.
And more he probably would have said,
had he not been interrupted by the officers who took him into custody,
and led him out of the building in order to carry him before my father.

When I understood this, I hastened home,
that I might give my father a fair account of the matter before the officers came.
I told him that the young man behaved himself quietly and peaceably,
that he spoke not a word until the minister had quite finished his service,
and that what he then spoke was but short,
and was delivered without passion or ill language.
This I knew would furnish my father with a fair ground
whereupon to discharge the man if he was willing.
And accordingly,
when the officers came and made their high complaint
against the man (who said little for himself),
my father, examined those who brought him concerning the words that he spoke,
about which they did not well agree.
And when they were asked concerning the time he had spoken them,
they all agreed that it was after the minister had finished;
and as for whether he had given the minister any reviling language,
or endeavored to raise a tumult among the people,
they admitted they could not charge him with any such thing.
Therefore, not finding that he had broken the law,
my father counseled the young man to be careful that he did not
occasion any further public disturbances--and so dismissed him;
which I was glad of.

Some time after this,
my father having heard a further account of the people called Quakers,
and being desirous to be informed concerning their principles,
made another visit to Isaac Penington and his wife
at their house called the Grange in Peter`'s Chalfont,
and he took both my sisters and myself along with him.

It was in the tenth month, in the year 1659, that we went there,
where we found a very kind reception, and tarried some days.
While we were there, a meeting was appointed at a place about a mile from their home,
to which we were invited to go, and willingly went.
It was held in a farm-house called The Grove,
which having formerly been a nobleman`'s residence, had a very large hall,
which the people well filled.

To this meeting came Edward Burrough, along with other preachers,
such as Thomas Curtis and James Nayler; but none spoke at that time but Edward Burrough.
It was my lot to sit on a stool next to him, by the side of a long table on which he sat,
and I drank in his words with eager desire; for they not only reached my understanding,
but also warmed my heart with a certain heat which I had
not till then felt from the ministry of any man.

When the meeting had ended, our friends took us home with them again; and after supper,
the evenings being long, the servants of the family (who were Quakers) were called in,
and we all sat down in silence.
But we had not sat long before Edward Burrough began to speak among us.
And although he spoke not long, yet what he said did touch, as I suppose,
my father`'s religious nerve, as the saying goes.
And he, having been from his youth a professor of religion,
though not joined in close communion with any one persuasion,
and valuing himself upon the knowledge he esteemed himself
to have of the various notions of each profession,
thought he had now a fair opportunity to display his knowledge,
and thereupon began to make objections against what had been delivered.
The subject of the discourse was the universal free grace of God to all mankind.
This he opposed with the Calvinistic tenet of particular and personal predestination.
But in his attempted defense of this indefensible notion,
he soon found himself more at a loss than he expected.
Edward Burrough said not much to him upon it,
though what he said was to the point and compelling.
But then James Nayler interposed,
and handled the subject with so much perspicuity and clear demonstration,
that his reasoning seemed irresistible; and so I suppose my father found it,
which made him quickly willing to drop the discourse.

As for Edward Burrough, he was a lively young man, of a ready tongue,
and might have been, for all I then knew, a scholar,
which made me less admire his way of reasoning.
But what dropped from the mouth of James Nayler had the greater force upon me,
because he looked but like a plain simple country-man,
having the appearance of a husbandman or a shepherd.

Seeing that my father was not able to maintain the argument on his side,
so neither did they seem willing to drive it on to an extremity on their side.
But treating him in a soft and gentle manner, after a while, they let fall the discourse,
and then we withdrew to our respective chambers.

The next morning we prepared to return home, that is, my father, my youngest sister,
and myself; for my eldest sister had gone before this time in a stage coach to London.
And when, having taken leave of our friends, we began to depart,
they accompanied us to the gate,
where Edward Burrough directed his speech in a few words to each of us individually,
according to the sense he had of our different conditions.
And when we had gone off, and they had returned to the house,
the Peningtons asked him what he thought of us.
He answered them (as they afterwards told me) to this effect: "`As for the old man,
he is settled in his ways, and the young woman is light and airy;
but the young man is reached, and may do well if he does not lose it.`"
And surely, the words which he had spoken to me,
or rather the Spirit by which he spoke them, took such fast hold on me,
that I felt sadness and trouble come over me,
though I did not distinctly understand why I was troubled.
I knew not what ailed me, but I knew that it was something more than ordinary,
and my heart was very heavy.

I found that this was not the case with my father and sister; for,
as I rode behind the coach, I could hear them talking pleasantly one to the other.
But they could not discern how it was with me, because, riding on horseback,
I kept much out of their sight.

By the time we got home it was night, and the next day, being the first-day of the week,
I went in the afternoon to hear the minister of Chinner.
This was the last time I ever went to hear any in that office.
After the sermon I went with with the minister to his house,
and in a freedom of discourse that I commonly used with
him because of a certain intimacy that was between us,
I told him where I had been, what company I had met with there,
and what observations I had made to myself upon the occasion.
He seemed to understand as little of them as I had understood before,
but civilly abstained from casting any unhandsome reflections on them.

I had a desire to go to another meeting of the Quakers,
and so I bid my father`'s servant to inquire if there was any in the country thereabouts.
He thereupon told me that he had heard at Isaac Penington`'s that
there was to be a meeting at High-wiccomb on Thursday next.
So there I went, though it was seven miles from me.
And in order that others might suppose I had gone hunting,
I let my greyhound run by my horse`'s side.

When I had come there, and had put up my horse at an inn,
I was at a loss how to find the house where the meeting was to be held.
I knew not where it was, and was ashamed to ask about it.
Wherefore, having requested the hostler^
footnote:[A person who has the care of horses at an inn.]
to take care of my dog, I went into the street and stood at the gate,
wondering what course to take.
But I had not stood long,
before I saw a man riding along in the street who
I remembered to have seen before at Isaac Penington`'s,
and he put up his horse at the same inn.
I therefore resolved to follow him, supposing he was going to the meeting,
as indeed he was.

Having come to the house (which proved to be John Raunce`'s)
I saw the people sitting together in an outer room.
I therefore stepped in and sat down on the first empty seat,
at the end of a bench just within the door,
having my sword at my side and black clothes on, which drew some eyes upon me.
It was not long before one stood up and spoke, whom I was afterwards well acquainted with.
His name was Samuel Thornton;
and what he spoke was very suitable and of good service to me,
for it reached home as if it had been directed to me.

As soon as the meeting had ended, and the people began to rise, I being next to the door,
stepped out quickly, hastened to the inn, and immediately returned home on my horse;
and so far as I remember, my having been gone was not taken notice of by my father.

This second meeting was like the clinching of a nail;
confirming and fastening in my mind those good principles
which had sunk into me at the former.
My understanding began to open, and I felt some stirrings in my breast,
tending to the work of a new creation in me.
The general trouble and confusion of mind which had
for some days lain heavy upon me and pressed me down,
without a distinct understanding of the particular cause for which it came,
began now to wear off, and some glimmerings of light began to break forth in me,
which let me see my inward state and condition towards God.
The light,
which before had shone in my darkness (when the darkness could not comprehend it),
now began to shine out of darkness,
and in some measure made known to me what it was that had before
clouded me and brought that sadness and trouble upon me.
I saw,
that although I had been in a great degree preserved from
the common immoralities and worst pollutions of the world,
yet the spirit of the world had hitherto ruled in me, and led me into pride, flattery,
vanity and superfluity; all of which were worthless.
I found that there were many plants growing in me
which were not of the heavenly Father`'s planting;
and that all these, of whatever sort or kind they were,
or however pleasing they might appear, must be plucked up.

Now all my former life began to be ripped up, and my sins, by degrees,
were set in order before me.
And though they looked not to be so black a color as those of the lewdest sort of people,
yet I found that all sin--that which has the fairest and finest appearance,
as well as that which is more coarse and foul--brought guilt, and with and for guilt,
it brought condemnation on the soul that sinned.
This I felt, and was greatly bowed down under the sense thereof.

I also then began to receive a new law, an inward law, superadded to the outward law,
namely,
"`the law of the Spirit of life in Christ Jesus,`" which wrought in me against all evil,
not only in deed and in word, but even in thought also;
so that everything was brought to judgment, and judgment passed upon all.
Thus I could no longer go on in my former ways and course of life, for when I did,
judgment took hold upon me for it.
Thus the Lord was graciously pleased to deal with me in a manner
somewhat like He had dealt with His people Israel of old;
for when they had transgressed His righteous law, and were called back by His prophet,
he bid them first to "`cease to do evil;`", and then to "`learn to do well,`"^
footnote:[Isaiah 1:16-17]
before He would allow them to reason with Him,
and before He would impart to them the effects of His free mercy (See Isaiah ch.
1).

I was now required by this inward and spiritual law--"`the law of the Spirit of life
in Christ Jesus`"--to "`put away the evil of my doings,`" and to "`cease to do evil.`"
And as for the particular evils which I was required to put away and cease from,
the measure of divine light (which was now made manifest
in me) began to show these unto me;
and whatever the light made manifest as evil, judgment then passed upon it.

So here a way began to be cast up before me to walk in^
footnote:[Isiah 57:14; 62:10]--a direct and plain way; so plain, that a way-faring man,
however weak and simple, though a fool in the wisdom and judgment of the world,
could not err, while he continued to walk in it;^
footnote:[Isaiah 35:8]
the error coming in only by man`'s going out of it.
And I saw that this _way_ was the measure of divine light that was manifested in me,
by which the evil of my doings was made known to me.

And by this divine light I then saw that,
though I needed not put away the evils of uncleanness, debauchery,
profaneness and the common pollutions of the world,
because through the great goodness of God and a civil education
I had been preserved out of these manifest evils;
yet I had many other evils to put away and to cease from.
Some of these were indeed not accounted evils by "`the world which lies in wickedness;`"^
footnote:[1 John 5:19]
but by the light of Christ they were made manifest to me as evils,
and so were condemned in me; as for instance,
those fruits and effects of pride that manifest themselves
in the vanity and superfluity of my apparel.
This, alas, I had taken much delight in, even as far as my ability would extend to.
Thus I was required to put away and cease from all such things;
and judgment lay heavy upon me until I did so.
Therefore, in obedience to the inward law,
which agreed with the outward (See 1 Tim. 2:9. Pet.
3:3. 1 Tim. 6:8. James 1:21),
I removed from my apparel all unnecessary trimmings of lace,
ribbons and useless buttons which had no real service,
but were only used as "`ornaments,`" and I also ceased to wear rings.

I was also required to put away and cease from the
custom of giving flattering titles to men.
This was an evil I had been much addicted to, and was considered quite an artist in it.
So from that time forward,
I dared not say "`sir,`" "`master,`" "`my lord,`" or "`madam,`" to any,
nor say "`your humble servant`" to any one to whom
I did not stand in the real relation of a servant;
which I had never done to any man.

Showing respect to particular persons by uncovering the head and bowing the knee
or body in salutations was a practice I had been much in the use of.
This is one of the vain customs of the world,
introduced by the spirit of the world in the place of true honor.
I saw it to be a false representation,
used in deceit as a token of respect by persons who
bear no real respect one to the other.
And besides,
this gesture is a type and proper emblem of that
divine honor which all ought to pay to Almighty God,
and which all Christians, of every persuasion, use when they offer their prayers to Him,
and therefore should not be given to men.
This I found to be another evil I had long been committing,
and was therefore now required to put it away and cease from it.

I had also been very accustomed to the corrupt and unsound
form of speaking in the plural number to a single person,
"`you`" to one, instead of "`thou,`" contrary to the pure, plain,
and single language of Truth, "`thou`" to one, and "`you`" to more than one,
which had always been used by God to men, and men to God, as well as one to another,
from the oldest record of time, until corrupt men, for corrupt ends,
in later and corrupt times, in order to flatter and fawn,
brought in that false and senseless way of speaking "`you`" to one;
which has since corrupted the modern language, and has greatly debased the spirits,
and depraved the manners of men.^
footnote:[At this time in history,
the correct and plain use of "`thee`" and "`thou`" to a single
person was beginning to give way to "`you`" and "`your.`"
Most modern English speakers are unaware that the words "`you`" and "`your`"
were originally _plural_ pronouns used only to address two or more people,
whereas "`thee`" and "`thou`" were used to address one person.
In the 1600`'s,
it became fashionable (as a means of showing honor or flattery) to use
the plural "`you`" or "`your`" in addressing people of higher social status,
while "`thee`" and "`thou`" were reserved for servants, children,
or people of lower social or economic position.
Early Friends stuck to what was then considered "`plain language`"
(using _thee_ and _thou_ to every single person, and you and your to two or more),
rather than showing partiality by addressing certain individuals in the plural.
However, throughout most of this journal,
thee and thou have been changed to you for the ease of the modern reader.]
These, and many more evil customs,
which had sprung up in the night of darkness and
general apostasy from the Truth and true religion,
were now by the in-shining of this pure ray of divine light in my conscience,
gradually revealed to be what I ought to cease from, shun,
and stand as a witness against.

But so subtly and powerfully did the enemy work upon the weak part in me,
that he persuaded me that I ought to make a difference
between my father and all other men in these things,
disusing these tokens of respect to others, yet still using them towards him,
as he was my father.
And so far did this ploy of his prevail upon me (through a fear lest I would do wrong
in withdrawing any sort of respect or honor from my father which was due unto him),
that being thereby beguiled,
I continued for a while to behave in the same manner
towards him with regard to both language and gesture,
as I had always done before.
And as long as I did so, standing bare-headed before him,
and giving him the accustomed language, he did not express any dislike of me.

But as to myself, and the work that had begun in me,
I soon found it was not enough for me to "`cease
to do evil;`" though this was a good step.
I had another lesson before me, which was,
to "`learn to do well;`" which I could by no means do, until I had truly given up,
with full purpose of mind, to cease from doing all evil.
And when I had done this,
the enemy then took advantage of my weakness to mislead me another way.

For I ought to have waited in the light for direction and guidance in the way of well-doing,
and not to have moved without the divine Spirit (a manifestation
of which the Lord had been pleased to give me to profit with^
footnote:[1 Corinthians 12:7]), but the enemy,
transforming himself into the appearance of an angel of light,
now offered himself to be my guide and leader into the performance of religious exercises.
And I, not then knowing the wiles of Satan,
and being eager to do some acceptable service to God,
too readily yielded myself to the guidance of my enemy, instead of my friend.

He thereupon humoring the fervor and zeal of my spirit,
put me upon religious performances in my own will, in my own time,
and in my own strength--things which in themselves were good,
and would have been profitable to me and acceptable
to the Lord if they had been performed in His will,
His time, and in the ability which He gives.
But these things being wrought in the will of man, and at the prompting of the evil one,
it is no wonder that it did me hurt instead of good.

I read abundantly in the Bible, and would assign myself tasks in reading;
requiring myself to read so many chapters,
sometimes a whole book or long epistle at a time.
I thought this time well-spent, though I was not much the wiser for all that I read;
for I read it too hastily, and without the true Guide, the Holy Spirit,
who alone could open my understanding and give a true sense of what was read.
I prayed often, and extended my prayers to a great length,
appointing certain set times to pray, and a certain number of prayers to say in a day;
yet meanwhile, I knew not what true prayer was.
For true prayer stands not in words,
even when words are uttered in the movings of the Holy Spirit;
but rather in the breathing of the soul to the heavenly
Father through the operation of the Holy Spirit,
who makes intercession--sometimes in words,
and sometimes with only sighs and groans--which the Lord mercifully hears and answers.

This will-worship^
footnote:[Colossians 2:23 KJV]--which all worship is that is performed in the
will of man and not in the movings of the Holy Spirit--was a great hurt to me,
and a hindrance to my spiritual growth in the way of Truth.
But my heavenly Father, who knew the sincerity of my soul before Him,
and the heartfelt desire I had to serve Him, had compassion on me;
and in due time was graciously pleased to illuminate my understanding further,
and to open in me an eye to discern the false spirit,
and its way of working from the true; and to reject the former and cleave to the latter.

But though the enemy had by his subtlety gained some advantages over me,
yet I nevertheless went on, and firmly persisted in my godly resolution of ceasing from,
and denying those things which I was now convinced in my conscience were evil.
And on this account a great trial came quickly on me.
For as the general Quarter Sessions for the peace was coming on,
and my father desired to excuse himself from the dirty journey,
he commanded me to arise early and go to Oxford,
and deliver the recognizances he had taken;
and also to bring him an account as to what justices were on the bench,
and what principal pleas were before them; all of which he knew I knew how to do,
having often attended him on such services previously.

But I, who knew how things stood with me far better than he did,
felt a weight come over me just as soon as he had spoken the words.
For I immediately saw that this would bring a very great exercise upon me.
Nevertheless, having never resisted his will in anything that was lawful (as this was),
I attempted not to make any excuse.
And ordering a horse to be ready for me early in the morning, I went to bed,
feeling great conflict in my breast.
For the enemy came in upon me like a flood, and presented many difficulties before me,
swelling them up to the highest pitch,
by representing them as mountains which I should never be able to get over.
And, alas, that faith which could remove such mountains and cast them into the sea,
was still but very small and weak in me.

He cast into my mind, not only how I must behave myself in court,
and dispatch the business for which I was sent;
but also how I must demean myself towards my acquaintances,
of whom I had many in the city, and with whom I had formerly been jolly,
whereas now I could not put off my hat, nor bow to any of them,
nor give them their honorary titles (as they are called),
nor use the corrupt language of "`you`" to any one of them,
but must keep to the plain language of "`thou`" and "`thee.`"
Much of this nature revolved in my mind,
being thrown in by the enemy to discourage and cast me down.
And I had none to turn to for counsel or help, but the Lord alone,
to whom I therefore poured forth my supplications
with earnest cries and breathings of soul,
that He, in whom was all power, would enable me to go through this great trial,
and keep me faithful to Himself therein.
And after some time, He was pleased to compose my mind to stillness,
and I was able to rest.

Early the next morning I got up, and found my spirit pretty calm and quiet,
yet not without a fear upon me lest I should slip
and let fall the testimony which I had to bear.
And as I rode, a frequent cry ran through me to the Lord, "`O my God,
preserve me faithful, whatever befalls me!
Permit me not to be drawn into evil,
no matter how much scorn and contempt may be cast upon me!`"

Thus was my spirit exercised on the way almost continually.
And when I came within a mile or two of the city, whom should I meet upon the way,
coming from there, but Edward Burrough!
I rode in a mountier-cap,^
footnote:[A winter hat, with flaps that protect the face from cold.]
a dress more common then than now, and so did he;
and because the weather was exceedingly frigid,
we had both had pulled our caps down to shelter our faces from the cold,
and by that means neither of us recognized the other,
but passed by without taking notice until a few days after, when meeting again,
and observing each others`' dress, we recollected where we had so lately met.
Then I thought to myself, "`O,
how glad I would have been to have received a word of encouragement and counsel from him,
when under that weighty exercise of mind!`"
But the Lord saw that it was not good for me, that my reliance might be wholly upon Him,
and not upon man.

When I had put up my horse,
I went directly to the hall where the court sessions were held,
and had been there a very short time before a group
of my old acquaintances saw me and drew near.
One of these was a scholar in his gown; another a surgeon of that city,
both my classmates and fellow-boarders at Thame school.
The third was a country gentleman, with whom I had long been very familiar.
When they had come up to me, they all saluted me after the usual manner,
putting off their hats, bowing, and saying, "`your humble servant,
sir;`" no doubt expecting the same from me.
But when they saw me stand still, not moving my cap,
nor bowing my knee in the way of compliment to them, they were amazed,
and looked first upon one another, and then upon me,
and then upon one another again for a while, without speaking a word.
At length the surgeon, a brisk young man, who stood nearest to me,
clapping his hand in a familiar way upon my shoulder, and smiling at me, said, "`What!
Tom, a Quaker?`"
To which I readily and cheerfully answered, "`Yes, a Quaker.`"
And as the words passed out of my mouth, I felt joy spring up in my heart;
for I rejoiced that I had not been drawn out into a compliance with them,
and that strength and boldness had been given me to confess
myself to be one of that despised people.

They stayed not long with me, nor said any more that I remember;
but looking somewhat confusedly upon one another, after a while they took their leave,
going off in the same ceremonious manner as they had come.

After they were gone, I walked a while around the hall,
and went up nearer to the court in order to observe both what justices were on the bench,
and what business they had before them.
This I did in fear, not of what they could or would have done to me,
but lest I should be surprised by any and drawn unwarily
into that which I was to keep out of.

It was not long before the court adjourned to go to dinner,
and I used that time to go to the clerk of the peace at his house,
with whom I was well acquainted.
As soon as I came into the room where he was, he came and met me,
and saluted me after his manner; for he had a great respect for my father,
and a kind regard for me.
And though he was at first somewhat startled at my conduct and language,
yet he treated me very civilly, without any reproach or jesting.
I delivered him the recognizances which my father had sent,
and having finished the business I had come upon, I withdrew,
and went to my inn to refresh myself, and then to return home.
But when I was ready to take horse, looking out into the street,
I saw two or three justices standing just in the way where I was to ride.
This brought a fresh concern upon me; for I knew if they saw me, they would recognize me.
And I concluded if they recognized me, they would stop me to inquire after my father;
and I doubted whether I would remain faithful to my convictions.

This doubting brought weakness over me,
and that weakness led me to contrive how I might avoid this trial.
I knew the city pretty well, and remembered there was a back road, which,
though somewhat out of my way,
would bring me out of town without passing by those justices;
yet I was unwilling to go that way.
I therefore stayed a little time, in hopes that they would have parted company,
or removed to some other place out of my way.
But when I had waited till I was uneasy for losing so much time,
and having entered into reasonings with flesh and blood,
the weakness prevailed over me and I took the back road;
which brought trouble and grief upon my spirit for having shunned the cross.

But the Lord looked on me with a tender eye,
and seeing that my heart was right towards Him,
and that what I had done was merely through weakness and fear of falling,
and also that I was sensible of my failure and sorry for it,
He was graciously pleased to pass it by, and to speak peace to me again.
When I went in the morning,
my heart was full of breathing prayer to the Lord that He would mercifully be with me,
and uphold and carry me through that day`'s exercise.
So now at my return in the evening, before I got home,
my heart was full of thankful acknowledgments and praises unto Him for His great
goodness and favor to me in having thus far preserved and kept me from falling
into anything that might have brought dishonor to His holy name,
the name I had now taken upon myself.

But notwithstanding it was thus with me,
and that I found peace and acceptance with the Lord in some good degree according
to my obedience to the convictions I had received by His Holy Spirit in me;
yet the veil was not fully rent,
for there still remained a cloud upon my understanding
with respect to my conduct towards my father.
And the notion which the enemy had brought into my mind--that I
ought to put such a difference between him and all others on the
account of paternal relation--did yet prevail with me.
Therefore, when I came home,
I went to my father and stood bare-headed before him as I was accustomed to do,
and gave him a particular account of the business in such a manner that he,
observing no alteration in my conduct towards him, found no cause to take offense at me.

I had felt for some time before this an earnest desire to go again
to Isaac Penington`'s. And I began to question whether,
when my father would come to understand that I inclined to settle among
the people called Quakers (as I was sure he would before long),
he would continue to allow me the use of his horses.
For this reason, the morning I had gone to Oxford,
I gave directions to a servant of his to go that day to a gentleman of
my acquaintance who I knew had a riding horse that he was willing to lend,
and to request, in my name, to send him to me.
This he did, and I found him in the stable when I came home.

On this horse I designed to ride the next day to Isaac Penington`'s;
and in order thereto, I arose early, and got myself ready for the journey.
But because I desired to pay all due respect to my father,
and not go without his consent, or at least without his knowledge,
I sent a servant up to him (for he was not yet stirring)
to acquaint him that I had a purpose to go to Isaac Penington`'s,
and I desired to know if he had any service for me to do.
He sent me word that he desired to speak with me before I went,
and would have me come up to him; which I did, and stood by his bedside.

Then in a mild and gentle tone he said,
"`I understand you have a mind to go to Mr. Penington`'s.`" I answered, "`I do.`"
"`Why,`" said he, "`I wonder why?
You were there, you know, but a few days ago, and unless you have business with them,
don`'t you think it will look odd?`"
I said, "`I do not think so.`"
"`Perhaps,`" said he, "`you will tire them with your company,
and make yourself a burden to them.`"
"`If,`" I replied, "`I find anything of that, I will make a shorter stay.`"
"`But,`" said he, "`can you propose any sort of business with them,
more than a mere visit?`"
"`Yes,`" said I, "`I propose not only to see them, but to have some discourse with them.`"
"`Why,`" said he, in a little harsher tone,
"`I hope you do not incline to be of their way.`"
"`Truly,`" I answered, "`I like them and their way very much,
so far as I yet understand it;
and I am willing to go to them that I may understand it better.`"

Thereupon my father began to list a catalog of faults against the Quakers;
telling me they were a rude and unmannerly people who would
not give civil respect or honor to their superiors,
nor to magistrates; that they held many dangerous principles;
that they were an immodest and shameless people;
and that one of them stripped himself stark naked,
and went in that unseemly manner about the streets, at fairs,
and on market-days in great towns.

To all the other charges,
I answered only that perhaps they might be either misreported or misunderstood,
as even the best of people had sometimes been.
But to the last charge, of going naked,
a particular answer by way of example was just then
brought into my mind and put into my mouth,
which I had not thought of before; the example of Isaiah,
who went naked among the people for a long time (Isaiah 20:4). "`Ah,`" said my father,
"`but you must consider that he was a prophet of the Lord,
and had an express command from God to do so.`"
"`Yes, sir,`" I replied, "`I do consider that;
but I also consider that the Jews among whom he lived
did not acknowledge him to be a prophet,
nor believe that he had such a command from God.
And,`" I added, "`how do we know that this Quaker is not a prophet too,
with a command to do as he did, for some reason which we understand not?`"

This put my father to a stand; so that letting fall his charges against the Quakers,
he only said, "`I wish you would not go so soon, but take a little time to consider it.
You may visit Mr. Penington another time.`"
"`No, sir,`" I replied, "`please don`'t hinder my going now,
for I have so strong a desire to go that I do not well know how to forbear.`"
And as I spoke those words, I withdrew gently to the chamber-door,
and then hastening downstairs, went immediately to the stable,
and finding my horse already bridled, I quickly mounted and went off,
lest I should receive a countermand.

This discourse with my father had somewhat delayed my journey,
and it being fifteen long miles there, the roads bad, and my horse but small,
it wasn`'t till the afternoon that I arrived.
And hearing from the servant who took my horse that
there was then a meeting in the house,
as there was weekly on that day, which was the fourth-day of the week, I hastened in.
Being familiar with the rooms, I went directly to the little parlor,
where I found a few Friends sitting together in silence,
and I sat down among them well-satisfied, though no words were spoken.

When the meeting had ended, and those of the company who were strangers had withdrawn,
I addressed myself to Isaac Penington and his wife, who received me courteously;
but not knowing what inward exercises I had been in, and was still under,
nor having heard anything of me since I had been there before in different apparel,
they were not hasty to "`lay hands upon me suddenly,`"^
footnote:[1 Timothy 5:22. A warning of Paul not to endorse or
recommend one into fellowship or ministry without due caution.]
which I observed and did not dislike.
But as they came to see a change in me, not only in my dress,
but in my conduct and speech, and what`'s more,
in my countenance also (for the exercises I had passed through and yet
was under had imprinted a visible character of gravity upon my face),
they were exceedingly kind and tender towards me.

There was then in the family a Friend whose name was Anne Curtis,
the wife of Thomas Curtis of Reading, who had come to visit them,
and particularly to see Mary Penington`'s daughter Gulielma,
who had been ill with the small-pox since I had been there before.
Between Mary Penington and this Friend,
I observed some private discourse and whisperings,
and I had an apprehension that it was about something that concerned me.
I therefore took the freedom to ask Mary Penington if my
coming there had occasioned any inconvenience in the family?
She asked me if I had had the small-pox?
I told her no.
She then told me that her daughter had recently had them,
and though she was well-recovered, she had not as yet been downstairs amongst them,
but intended to come down and sit with them in the parlor that evening;
yet she would rather wait till another time than endanger me.
This was the matter they had been discussing.
I assured her that I had always been, and was then more especially,
free from any apprehension of danger in that respect;
and I therefore entreated that her daughter might come down.
Although they seemed somewhat unwilling to yield to it out of concern for me,
yet my importunity prevailed, and after supper she did come down and sit with us.
And though the marks of the distemper were fresh upon her,
yet they made no impression upon me, faith keeping out all fear.

We spent much of the evening in retiredness,
our spirits being weightily gathered inward unto the Lord;
so that not much discourse passed among us, neither they to me, nor I to them.
Yet I had good satisfaction in this stillness, feeling my spirit drawn near to the Lord,
and to them in Him.
Before I went to bed,
they let me know that there was to be a meeting at Wiccomb the next day,
and that some of the family would attend.
I was very glad of it, for I greatly desired to go to meetings,
and this one would be very convenient, being directly on my way home.
The next morning Isaac Penington went, having Anne Curtis with him,
and I accompanied them.

At Wiccomb we met with Edward Burrough who came there from Oxford,
where I had seen him some days before when, both having our mountier-caps on,
we had passed by each other on the road unknown.
But now we recollected that we had recently met.

This was a monthly meeting,
consisting chiefly of Friends who gathered to it from several parts of the country thereabouts;
so that it was pretty large.
It was held in a room in Jeremiah Stevens`' house,
as the room where we had met before in John Raunce`'s house was too small to receive us.
And a very good meeting this was to me.
Edward Burrough`'s ministry came forth among us in life and power,
and the assembly was covered therewith.
I also, according to my small capacity, experienced a share in it.
For I felt some of that divine power working my spirit into a great tenderness,
and not only confirming me in the course I had already entered,
and strengthening me to go on therein,
but also rending the veil somewhat further and clearing my understanding
in some other things which I had not seen before.
For the Lord was pleased to make His discoveries to me by degrees,
that the sight of too great a work, and too many enemies to encounter at once,
might not discourage and make me faint.

When the meeting had ended,
the Friends of the town taking notice that I was
the man who had been at their meeting the week before,
whom they then did not know, some of them came and spoke lovingly to me,
and requested me to stay with them; but Edward Burrough going home with Isaac Penington,
invited me to go back with him, which I willingly consented to.
For the love I had more particularly to Edward Burrough,
through whose ministry I had received the first awakening stroke,
drew me to desire his company, and so away we rode together.

But I was somewhat disappointed of my expectation;
for I hoped he would have given me both opportunity
and encouragement to open myself to him,
and to pour forth my complaints, fears, doubts and questions into his bosom.
But he, being sensible that I was truly reached,
and that the witness of God was raised in me,
and the work of God rightly begun--chose to leave
me to the guidance of the good Spirit in myself,
the Counsellor that could resolve all doubts,
that I might not have any dependence on man.
Therefore, although he was naturally of an open and free disposition and conduct,
and was afterwards always very familiar and affectionately kind to me,
yet at this time he kept himself somewhat reserved and showed only common kindness to me.

The next day we parted, he for London, and I for home,
under a very great weight and exercise upon my spirit.
For I now saw, in and by the further openings of the divine light in me, that the enemy,
by his false reasonings,
had beguiled and misled me with respect to my conduct towards my father;
and that the honor due to parents did not consist
in uncovering the head and bowing before them,
but in a ready obedience to their lawful commands,
and in performing all needful services to them.
Therefore,
as I was greatly troubled for what I already had
done in that case (though it was through ignorance),
so I plainly felt I could no longer continue therein without
drawing on myself the guilt of willful disobedience,
which I well knew would draw after it divine displeasure and judgment.

Hereupon the enemy assaulted me afresh,
setting before me the danger I would run myself into
by provoking my father to use severity towards me,
and perhaps to cast me utterly off.
But the Lord, unto whom I cried, supported me over this temptation,
and gave me faith to believe that He would bear me
up through whatever might befall me on that account.
I therefore resolved, in the strength which He would give me,
to be faithful to His requirings, whatever might come of it.

Thus, laboring under various exercises on the way, I at length arrived home,
expecting I would meet with a rough reception from my father.
But when I came home, I found that my father was away from home.
I therefore sat down by the fire in the kitchen, keeping my mind retired to the Lord,
with breathings of spirit unto Him that I might be preserved from falling.

After some time I heard the coach drive in, which put me into a little fear,
and a sort of shivering came over me.
But by the time he had alighted from the coach and come in,
I had pretty well recovered myself.
As soon as I saw him, I rose up, advanced a step or two towards him,
and with my hat still on, said,
"`Isaac Penington and his wife remember their love to thee.`"

He made a stop to hear what I said,
and observing that I did not stand before him uncovered,
and that I used the word "`thee`" to him; he, with a stern countenance,
and a tone that spoke great displeasure, only said, "`I shall talk with you, sir,
another time!`"
So, hastening from me, he went into the parlor, and I saw him no more that night.

Though I foresaw that there was a storm arising,
the apprehension of which was unsettling to me,
yet the peace which I felt in my own breast raised in me
a return of thanksgivings to the Lord for His gracious supporting
hand which had thus far carried me through this difficulty.
And humble cries were raised in spirit to Him that He would
mercifully stand by me to the end and uphold me,
that I might not fall.

My spirit longed to be among Friends, and to be at some meeting with them on first-day,
which was approaching, this being the sixth-day night.
I therefore proposed to go to Oxford the next day, which was the seventh-day of the week,
having heard there would be a meeting there.
Accordingly, having ordered my horse to be made ready early,
I got up in the morning and made myself ready also.
Yet before I left,
in order that I might be as observant to my father as I possibly could,
I requested my sister to go up to him in his chamber
and acquaint him that I had a mind to go to Oxford,
and I desired to know if he had any service for me to do there.
He bid her tell me not to go until he had spoken with me.
And getting up immediately, he hastened down to me before he was quite dressed.

As soon as he saw me standing with my hat on, his passion transported him,
and he fell upon me with both his fists.
And having by that means somewhat vented his anger,
he plucked off my hat and threw it away.
Then, stepping hastily out to the stable and seeing my
borrowed horse stand ready saddled and bridled,
he asked his servant where the horse came from?
The servant telling him he had fetched it from Mr. Barton, my father replied,
"`Then ride him back immediately,
and tell Mr. Barton that I desire him never to lend my son a horse again,
unless he bring a note from me.`"
The poor fellow, who loved me well, would eagerly have made excuses for me,
but my father was positive in his command,
and was so urgent that he would not let him stay so long as to eat his breakfast,
though he had five miles to ride; nor would my father leave the stable,
until he had seen the man mounted and gone.

Then, coming in, he went up into his chamber to make himself more ready,
thinking he had confined me me to the house now that my horse was gone;
for I took so much delight in riding, that I seldom went anywhere on foot.
But while he was dressing himself in his chamber, I changed my riding boots for shoes,
took another hat, and then acquainting my sister (who loved me very much,
and in whom I could confide) where I intended to go,
I went out alone and walked away to Wiccomb, having seven miles to go,
which yet seemed little and easy to me from the desire I had to be among Friends.

But as I travelled alone--under a load of grief from the sense
I had of the opposition and hardship I was to expect from my father--the
enemy took the opportunity to assault me again,
casting a doubt into my mind whether I had done well in thus coming
away from my father without his permission or knowledge.
I was quiet and peaceable in my spirit before this question darted into my mind;
but afterwards, disturbance and trouble seized upon me,
so that I was at a stand what to do, whether to go forward or backward.
Fear of offending inclined me to go back;
but a desire to be in the meeting with Friends pressed me to go forward;
so I stood still a while to consider and weigh the matter as well as I could.
I was satisfied that I had not left my father with
any intention of undutifulness or disrespect to him;
but merely in obedience to that drawing of Spirit (which I was persuaded
was of the Lord) to join with His people in worshipping Him,
and this made me feel easy.

But then the enemy, to make me uneasy again, objected:
How could a drawing be of the Lord which drew me to disobey my father?
I thereupon began to consider the extent of paternal power;
which I found was not wholly arbitrary and unlimited, but had bounds set to it; namely,
that in civil matters, it was confined to things lawful;
and that in spiritual and religious matters it had no compulsory power over our conscience,
which always ought to be subject to our heavenly Father.
And therefore, though obedience to parents is required of children,
yet it is given with this limitation, "`in the Lord:`" "`Children,
obey your parents _in the Lord;_ for this is right.`"^
footnote:[Ephesians 6:1]

This tipped the scale for going forward, and so on I went.
And yet I was not wholly free from some fluctuations
of mind from the besetments of the enemy.
Therefore,
although I knew that outward signs did not properly belong to the gospel dispensation,
yet for my better assurance,
in fear and great humility I beseeched the Lord that He would be pleased
to condescend to the weakness of His servant and grant me a sign by which
I might certainly know whether my way was right before Him or not?

The sign which I asked for was, that if I had done wrong in coming as I did,
I might be rejected or coldly received at the place where I was going.
But if my undertaking was right in His sight,
He would give me favor with those I went to,
so that they would receive me with hearty kindness and demonstrations of love.
Accordingly, when I came to John Raunce`'s house,
where I chose to go because the meeting was commonly held there,
they received me with more than ordinary kindness, especially Frances Raunce,
John Raunce`'s wife, who was both a grave and motherly woman,
and had a hearty love to Truth,
and tenderness towards all that in sincerity sought after it.
This kind reception,
confirming me in the belief that my undertaking was approved of by the Lord,
gave great satisfaction and ease to my mind, and I was thankful for it to the Lord.

Thus it fared with me there; but at home it fared otherwise with my father.
He supposing I had gone up to my chamber when he took my hat from me,
made no inquiry about me until evening came.
Then sitting by the fire, and considering that the weather was very cold,
he said to my sister who sat by him, "`Go up to your brother`'s chamber,
and call him down.
Otherwise he may sit there in a sullen fit until he has caught cold.`"
"`Alas sir,`" said she, "`he is not in his chamber, nor in the house either.`"
At that my father was surprised and said, "`Where is he then?`"
"`I know not, sir, where he is;`" she said,
"`but I know that when he saw that you had sent away his horse,
he put on shoes and went out on foot, and I have not seen him since.
And indeed, sir,`" she added, "`I don`'t wonder at his going away,
considering how you treated him.`"
This put my father into a great fright, believing I had left home for good.
Indeed,
a great passion of grief seized upon him and he could
not keep himself from weeping and crying out aloud,
so that all the family heard him, "`Oh, my son!
I shall never see him again!
For he is of so bold and resolute a spirit, that he will run himself into danger,
and so may be thrown into some jail or other,
where he may lie and die before I can hear of him.`"
Then bidding her to take him to his chamber, he went immediately to bed,
where he lay restless and groaning,
and often bemoaning himself and me for the greatest part of the night.

The next morning my sister sent a servant, whom because of his love to me,
she knew she could trust, to give me this account.
And though she also sent with him fresh linen for my use,
in case I should go further or stay out longer,
yet she requested me to come home as soon as I could.

This account left me very uneasy,
for I was much grieved that I had occasioned so much grief to my father.
I would have returned that evening after the meeting,
but the Friends would not permit it; for the meeting ended late,
the days were then short, and the way was long and dirty.
And besides this,
John Raunce told me that he had something on his mind to speak to my father,
and that if I would stay till the next day, he would go there with me;
perhaps hoping that, while my father was under this sorrow for me,
his heart might be the more open.
Hereupon, concluding to stay till the morning,
I dismissed the man with the things he brought,
bidding him tell my sister that I intended, God willing, to return home tomorrow;
and charging him not to let anybody else know that he had seen me, or where he had been.

Next morning John Raunce and I set out,
and when we had come to the outskirts of the town,
we agreed that he would go before me and knock at the great gate,
and I would come a little after him and go in by the back way.
He did so; and when a servant came to open the gate,
John asked if the justice was at home.
She told him, "`yes;`" and requested him to come in and sit down in the hall,
and then went and acquainted her master that a man
had come who desired to speak with him.
My father, supposing it was one that had come on business,
went readily into the hall to him.
But he was not a little surprised when he found that it was a Quaker;
yet not knowing for what purpose he came, he stayed to hear his business.
But when he found that it was about me, he spoke to him somewhat sharply.

By this time I had come by the back way into the kitchen,
and hearing my father`'s voice so loud, I began to doubt that things were going well;
and I was soon assured of this.
For my father quickly having enough of a Quaker`'s company,
left John Raunce in the hall and came into the kitchen,
where he was even more surprised to find me.
The sight of my hat upon my head,
made him presently forget that I was that son of
his whom he had so lately lamented as lost.
And feeling his passion of grief quickly turn to into anger,
he was unable to contain himself, and ran upon me with both his hands.
He first violently snatched off my hat and threw it away, and then,
giving me some blows on my head, said, "`Sirrah,^
footnote:[_Sirrah_ was a word of reproach or contempt, used in addressing vile characters.]
get up to your chamber!`"
I immediately went, he following close at my heels,
and now and then giving me a blow on the ear.
And as the way to my chamber passed through the hall where John Raunce was,
he (poor man) had to witness the scene, and was no doubt was sorry,
but could do nothing to help me.

This was truly an unexplainable thing, that my father would, one day before,
express so great a sorrow for me as fearing he should never see me any more; and yet now,
as soon as he did see me, fly upon me with such violence,
and only because I did not put off my hat,
which he well knew I did not keep on in disrespect to him,
but only upon a religious principle.
But as this hat honor had grown to be a great idol, in those times more especially,
so the Lord was pleased to engage his servants in a steady testimony against it,
whatever suffering was brought upon them for it.
And though some, who perhaps have been called into the Lord`'s vineyard at later hours,
after the heat of that day has largely passed,
may be apt to account this testimony a small thing to suffer so much upon,
as some have done--not only beatings, but fines,
and long and hard imprisonments--yet in those times,
those who were faithfully exercised under it dared not "`despise the day of small things;`"^
footnote:[Zechariah 4:10]
knowing that he who would do so,
would not be thought worthy to hold forth greater testimonies.

I had now lost one of my hats, and I had but one more.
I therefore put my second hat on, but did not keep it long;
for the next time my father saw it on my head, he tore it violently from me,
and put it with the other, I knew not where.
I therefore put on my mountier-cap, which was all I had left to wear on my head.
But it was very little while that I kept it, for as soon as my father came where I was,
I lost that one too.
I was now forced to go bare-headed wherever I had occasion to go,
both within doors and without.
This was in the eleventh month, called January,^
footnote:[Until 1752,
March was considered the first month of the year in all of England and its colonies.]
and the weather was piercing; so that I, who had been bred up more tenderly,
took so great a cold in my head that my face and head were much swollen,
and my gums had such great sores on them, that I could neither chew meat,
nor swallow liquids without difficulty.
This sickness held a long time, and I underwent much pain without much pity,
except from my poor sister, who did what she could to give me ease.

I was held as a sort of prisoner for the rest of the winter,
having no means to go out among Friends, nor did they have liberty to come to me.
I therefore spent the time mostly in my chamber, in waiting on the Lord, and in reading,
mostly in the Bible.
But whenever I had occasion to speak to my father, though I now had no hat to offend him,
yet my language did as much.
For I dared not say "`you`" to him,
but only "`thou,`" or "`thee,`" as the occasion required,
and then he would be sure to strike me with his fists.

I remember at one of these times, after he had beaten me in this manner,
he commanded me (as he commonly did at such times) to go to my chamber.
This I did, as he followed me to the bottom of the stairs and gave me a parting blow.
Then, in a very angry tone, he said, "`Sirrah,
if I ever hear you say _thou_ or _thee_ to me again,
I`'ll strike your teeth down your throat!`"
I was greatly grieved to hear him speak in this way;
and feeling a word rise up in my heart, I turned again and calmly said to him,
"`Would it not be just, if God should treat thee so when thou say _thou_ or _thee_ to Him?`"^
footnote:[Ironically,
though many at this time considered it belittling to be
referred to with the single pronouns _thou_ and _thee,_
yet every Christian, of every denomination and persuasion,
uniformly used these pronouns to address their Creator in prayer.]
Though his hand was then up, I saw it sink down and his countenance fall,
and he turned away and left me standing there.
I nevertheless went up into my chamber and cried unto the Lord,
earnestly beseeching Him that He would be pleased to open my father`'s eyes,
that he might see who he fought against, and for what purpose;
and that he would turn his heart.

After this I had a short time of rest and quiet from these
disturbances wherein my father said nothing to me,
nor gave me occasion to say anything to him.
I was still under a kind of confinement, but I found that,
though to be abroad and at liberty among my friends would have been more pleasant to me,
yet home was at present my proper place,
and was like a school in which I was to learn with patience to bear the cross,
so that I willingly submitted to it.

But after a little time,
a fresh storm--more fierce and sharp than any before--arose and fell upon me;
the occasion whereof was this: My father, having been in his younger years,
more especially while he lived in London,
a constant hearer of those who are called puritan preachers,
had stored up a pretty significant stock of Scripture knowledge, and sometimes,
though not constantly nor very often,
caused his family to come together on first-days in the
evening to expound a chapter to them and to pray.
His family now, as well as his estate, was smaller; for my mother was dead,
my brother gone, and my eldest sister in London.
And having put off his husbandry, he had put off along with it most of his servants,
so that he now had but one man and one maid servant.
It so happened, that on a first-day night, he bid my sister,
who sat with him in the parlor, to call in the servants for prayer.

Whether this was done intentionally as a trial upon me, I do not know;
but a trial it certainly proved to me.
For the servants, loving me very well, and disliking my father`'s conduct towards me,
made no haste to go in, but stayed for a second summons.
This so offended my father, that when at length they did go in, instead of praying,
he questioned them as to why they did not come when they were first called?
The answer they gave him being such as heightened, rather than abated, his displeasure,
he, with an angry tone said, "`Call in that fellow,`" meaning me,
who was left alone in the kitchen, "`for he is the cause of all this!`"
As they had been slow to go in themselves, so they were also reluctant to call me in,
fearing that the effect of my father`'s displeasure would fall upon me, as it soon did;
for hearing what was said, and not staying for the call, I went in of my own accord.
As soon as I had come in,
my father discharged his displeasure on me in very sharp and bitter expressions; which,
seeing him so transported with passion,
drew from me (in the grief of my heart) the following words:
"`Those who can pray in such a spirit, let them; as for my part, I cannot.`"
Hearing these words, my father flew upon me with both of his fists; and then,
thinking that not sufficient, stepped hastily to the place where his cane stood,
and picking it up, began to lay it on me, I thought, with all of his strength.
Being bare-headed, I thought his blows must certainly have broken my skull,
had I not laid my arm over my head to defend it.

My father`'s servant seeing this, and not able to contain himself,
stepped between us and laid hold of the cane.
Though he did not attempt to take it away,
yet by the strength of his hand he held it so tightly that he kept my father from striking,
which only enraged him the more.
I disliked this interposition on his part,
and told him to let go of the cane and be gone; which he immediately did,
and turning to leave, he received a blow on the shoulders for his efforts,
which yet did not much hurt him.

But now my sister, fearing that my father would take up striking me again,
entreated him to desist; adding, "`Truly sir, if you strike him any more,
I will throw open the window and cry murder; for I am afraid you will kill my brother.`"
This stopped his hand; and after some threatening speeches,
he commanded me to get to my chamber, which I did--as I always did whenever he bid me.
My sister soon followed me to see my arm and to dress the wounds,
for my arm was indeed very much bruised and swollen between the wrist and elbow,
and in some places the skin was broken and beaten off.
But though it was very sore, and for some time I felt much pain in it,
yet I had peace and quietness in my mind,
being more grieved for my father than for myself,
who I knew had hurt himself more than me.

This was, as far as I remember,
the last time that my father ever called his family to prayer.
And this was also the last time that he ever thus abused me, at least so severely.
Soon after this, my eldest sister, who in all this time had been in London, returned home.
She was much troubled to find me a Quaker,
a name of reproach and great contempt at that time; and she, having been in London,
no doubt heard the worst representation of them.
Yet, though she disliked the people,
her affectionate regard to me made her rather pity than despise me; and the more,
when she understood what hard treatment I had met with from my father.

The rest of this winter I spent in a lonesome solitary life,
having none to converse with, none to open myself to, none to ask counsel of,
none to seek relief from, but the Lord alone; who yet was more than all.
And yet the company and society of faithful and judicious friends, would, I thought,
have been very welcome to me, as well as helpful in my spiritual travel.
Indeed, I thought I made but slow progress,
and my soul continually breathed after further growth;
the sense of which drew from me the following lines:

The winter tree

Resembles me,

Whose sap lies in its root:

The spring draws nigh;

As it, so I

Shall bud, I hope, and shoot.

At length it pleased the Lord to move Isaac Penington
and his wife to make a visit to my father,
to see how it fared with me.
They tarried with us all night,
and had much discourse with my father both about the principles of Truth in general,
and about me in particular, which I was not privy to.
But one thing that I remember afterwards hearing of was this:
When my father and I were at their house some months before, Mary Penington,
in some discourse between them, had told him how roughly her husband`'s father,
alderman Penington,^
footnote:[Isaac Penington`'s Father (Sir Isaac Pennington Sr. 1584-1661) was
a well-known English politician and Puritan Congregationalist who sat on the
House of Commons from 1640 to 1653 and was Lord Mayor of London in 1642 and 1643.
He was a member of the tribunal that convicted Charles I of treason and executed him,
and afterwards became a prominent member of Oliver Cromwell`'s government.
With the Restoration of Charles II in 1660,
Pennington Sr. was tried for high treason and imprisoned in the Tower of London,
where he died awaiting execution on December 16, 1661.
(Isaac Penington Jr. dropped an "`n`" from his name,
perhaps so as not to be confused with his father.)]
had treated him because of his hat.
My father--little then thinking that it would so soon be his own
case--did very much censure the alderman for such behavior,
wondering why so wise a man as he would take notice
of such a trivial thing as the putting off,
or keeping on of a hat; and he did not refrain from blaming him liberally for it.

This gave her a handle, so to speak, by which to take hold of him.
And having had a long acquaintance with him,
and he having always had a high opinion and respect for her; she,
who was a woman of great wisdom, of ready speech, and of a well-resolved spirit,
did press him so closely with this argument,
that he was utterly at a loss how to defend himself.

After dinner the next day, when they were ready to take coach and return home,
she requested my father, that since my company was so little acceptable to him,
he would give me permission to go and spend some time with them,
where I would be sure to be welcome.
At first he was very unwilling to let me go, and made many objections against it.
But all of these she answered and removed so clearly, that,
not finding any further excuse to allege, he at length left it up to me;
and I quickly tipped the scale for going.

We had come to the side of the coach before this was concluded,
and I was ready to step in when one of my sisters privately
informed my father that I did not have a hat on.
This somewhat startled him,
for he did not think it fitting that I should leave home and stay abroad without a hat.
He therefore whispered to her to fetch me a hat,
and he entertained the Peningtons with some discourse in the meantime.
But as soon as he saw the hat coming, he would not stay till it came,
lest I should put it on in his presence.
And so, breaking off his discourse abruptly, he took his leave of them,
and hastened inside before the hat was brought to me.

Oh, great was the love and manifold the kindnesses which
I received from these my worthy friends,
Isaac and Mary Penington, while I abode in their family.
They were indeed as affectionate parents and tender nurses to me,
in this time of my spiritual childhood.
For in addition to their weighty and seasonable counsel, and their exemplary conduct,
they furnished me with the means to go to other meetings of Friends in that county,
whenever the meeting was not in their own house.
And, indeed, the time I stayed with them was so well spent,
that it not only yielded great satisfaction to my mind, but turned, in good measure,
to my spiritual advantage in the Truth.
The Lord was graciously pleased to visit me by his quickening Spirit and life,
so that I came to feel the operation of His power in my heart,
working out that which was contrary to His will, and giving me, in measure,
dominion over it.

[.asterism]
'''

Thomas Ellwood continued in heartfelt submission to the Spirit of Truth and so grew
to become an esteemed elder and a very useful member of the early Society of Friends.
Joseph Wyeth, in describing his character, says: "`He was a man of a comely aspect,
of a free and generous disposition, of a courteous and affable temper,
and pleasant conversation; a gentleman, a scholar, a true Christian, an eminent author,
a good neighbour, and kind friend.`"
For many years, Thomas Ellwood was very busy with his pen in defending the Truth,
publishing several books and treatises in response to the various slanders
and misrepresentations that were printed by opponents of the Society.
He also published a lengthy historical work on both the Old and New Testaments,
called "`Sacred History,`" and a poetic piece called "`Davideis`" on the life of David,
king of Israel.
However he is probably best known for being the original
editor and publisher of the Journal of George Fox,
which was first printed in 1694.
In the year 1713,
after apparently suffering from a stroke and becoming
paralyzed on the right side of his body,
his health quickly gave way and he departed this
life in the seventy-fourth year of his age.
When very close to his end, in the presence of some friends,
he announced in much brokenness of heart, "`I am full of joy and peace.
My spirit is filled with joy.`"
