[quote.epigraph, , Heb. 11:2]
____
By faith the elders obtained a good report.
____

== Preface

"`Gather up the fragments that remain,
that nothing be lost,`" was the direction of our Saviour to his disciples,
after he had fed the multitude.
This may properly be applied to collecting and
preserving the accounts of the lives of good men,
who in their day have been eminently useful in those stations of life wherein God,
by his good providence, hath placed them.
And this is the rather to be done, when themselves leave behind them, in writing,
an account of their lives, and of the signal mercies of God to them therein.
From such accounts may best be gathered, their particular state,
exercise and growth in the work of restoration out of the fall and degeneracy; and,
in the reading thereof, we may be not only incited to bless the name of the Lord,
on their behalf, but also gain some instruction from the path so fairly tract out,
and their ground of hope; that by being faithful,
we may likewise attain the same good experience.

There is not with me any doubt but something of this kind may be the lot of many,
into whose hands this treatise may happen to come;
for they will herein meet with a variety of exercises,
and the providences of God therein, related with strength and plainness of speech.
Our deceased friend Thomas Ellwood,
was a man whom God had endued with singular abilities, both as a man, and as a Christian;
which is evident,
from his many useful labours and services and the many
books which he wrote in the defence of Truth,
and the friends thereof For this service,
he was in a particular manner qualified by spiritual wisdom and Christian obedience;
to which, in him, was added great strength and depth of judgment,
wherein he could discern the spirits of others, and was very much the master of his own,
as appeared to such who knew him,
not only by the soundness of his reasoning and the seasonableness of his words;
but also by his great and exemplary modesty, in that he was not hasty to propose,
nor rudely tenacious to insist on what he had proposed, if any thing,
though not well expressed, yet well intended, was offered by any I one much weaker, nay,
though by but a babe in Christ.

His countenance was manly and cheerful; his deportment grave, yet affable and courteous,
even to the meanest person; his conversation innocent, pleasant and instructive,
yet severe against any thing that was beyond the liberty of truth.
These, with his other qualifications of body and mind,
rendered him very acceptable and useful, as a friend and as a neighbour,
and as a member and elder in the church of Christ; and the more,
for that his time was chiefly employed in being
serviceable in one or other of these capacities.

I might here particularly mention the labours of our deceased friend,
according to their respective times, and the nature of their several subjects;
but much of this being already done in the ensuing pages, I choose to omit it; by which,
possibly the reader may be incited to the perusal of them;
and shall only say concerning them,
that his method and style denote him to have been a scholar; and yet not farther so,
than the simplicity and purity of the truth, whereof he made profession,
would permit him.

As it was my lot to be well acquainted with him,
though only in the latter years of his life,
and I know that he did neither use nor encourage the
bestowing elaborate encomiums upon persons deceased;
so I shall add no further concerning him,
than to say with the apostle concerning the faithful, "`That he was righteous,
God testifying of his gifts; and by it being dead, he yet speaketh.`"

[.signed-section-signature]
Joseph Wyeth.

[.signed-section-context-close]
London, the 12th of the Second month, 1714.
