== Appendix

[.chapter-subtitle--blurb]
Containing a Supplementary Memoir of the Life of Thomas Ellwood.

It does not appear that Thomas Ellwood left any account of his own life,
subsequent to the close of 1683, the period at which the preceding memoir concludes;
though from thence to the time of his decease, an interval elapsed of about thirty years.
During that time his active pen was employed, with but little intermission,
in support of the cause, to the service of which his heart and talents were devoted.
To this circumstance may reasonably be attributed the deficiency in his narrative;
which the following pages,
comprising a brief notice of the principal
circumstances that have been handed down to us,
relating to that portion of his life, may in some measure supply.

In consequence of the imprisonment of Friends under the Riot Act, noticed in page 415,
etc., Thomas Ellwood published, in the course of the same year,
"`A Discourse concerning riots:
occasioned by some of the people called Quakers being indicted for a riot,`" etc.
The objects of this tract were,
to define the legal signification of the term "`riot;`" and to prove
that the meetings of Friends in no degree partook of that character.
The following are extracts from the concluding observations:
"`How truly I have stated the case on the one hand, with respect to riots,
the many quotations in the foregoing discourse will show.
How true an account, on the other hand, I have given of our meetings, the whole nation,
and all nations where we have meetings, may judge.
Upon the whole, my request is, that all, both justices and jurors,
who have or shall be concerned in this or the like case, will seriously weigh the matter,
and not strain the law beyond its due extent.`"
"`To oppress any by colour of law, is the greatest abuse of law.`"

In the same year he addressed a forcible yet temperate remonstrance,
to those whose eyes were not open to the impiety and
absurdity of attempting to exact religious compliances;
which he entitled, "`A seasonable Dissuasive from persecution, humbly and modestly,
yet with Christian freedom and plainness of speech,
offered to the consideration of all concerned therein;
on behalf generally of all that suffer for conscience`' sake;
particularly the people called Quakers.`"

The following extracts comprise the author`'s introduction of his subject,
and the heads of his arguments:

"`Persecution is a word of so harsh a sound,
and so generally distasteful to English ears,
that scarcely any of those who are most forward and active in that work,
are willing to have their actions called by that name.
That none therefore, who have set a hand to that work,
or whose minds are any whit inclined thereto, may,
from the dislike they have to the word,
reject this dissuasive as a thing wherein they are not concerned;
I think it needful here to declare, what it is I mean by persecution.
By persecution, then, I intend a forcing or compelling of any, by pains or penalties,
bodily or pecuniary, to relinquish or forsake that exercise of religion,
or way of worship, which they believe to be the right way of worship,
and the true and acceptable exercise of religion, which God hath required of them:
and to receive, embrace, conform to,
and perform some other exercise of religion and way of worship,
which they who are so compelled are either firmly persuaded is not right,
or at least have no belief that it is right.

"`This, in short, is that which I call persecution; and this is that which I dissuade from,
whatever other name the actors of it may please themselves in calling it by.

[.embedded-content-document.paper]
--

[.numbered]
"`I. To begin now with the first of these, viz:
the forcing or compelling of any to forsake that exercise of religion, or way of worship,
which they believe to be right:--the reasons by which I shall
endeavour to dissuade all men from such an undertaking,
are these:

[.numbered]
--"`1. You may, for aught you know, be found fighting against God: you are not,
you cannot be, upon your own principles, infallibly sure,
that that way of worship which you thus endeavour to force us from,
is not the true worship of God.

[.numbered]
--"`2. By endeavouring to force us from that way of worship,
which we believe the Lord hath led us into, and requireth of us,
you endeavour to force us to make shipwreck of faith.

[.numbered]
--"`3. In endeavouring, by force and cruelty, to restrain us from worshipping God,
as we are fully persuaded he hath taught us and doth require of us,
you go out of the path of the righteous,
and tread in the steps of the wicked and ungodly.

[.numbered]
--"`4. That exercise of religion which you would force us from,
is not simply of itself condemned and disallowed by that law,
by the severity of which you would force us from it.

[.numbered]
--"`5. In thus eagerly pursuing us, and disturbing our peaceable meetings,
you give yourselves, as well as us, a great deal of needless trouble.
For, as that learned doctor in the Jewish law did well observe,
'`if this counsel or this work be of men, it will come to naught; but if it be of God,
ye cannot overthrow it:`'--so I say to you in our case.

[.numbered]
--"`6. And lastly, be pleased to consider,
what sort of agents and instruments you are fain to make use of,
and not seldom are yourselves made use of by, to carry on this work.`"

[.numbered]
"`II. Now for the other branch of persecution, viz:
The forcing or compelling of any to embrace some exercise of religion and way of worship,
which they are firmly persuaded is not right,
or at least have no belief that it is right:
the reasons by which I shall endeavour to dissuade all men from such an undertaking,
are these:

[.numbered]
--"`1. In thus imposing your way of worship upon others,
you act quite contrary to Christ and his apostles.

[.numbered]
--"`2. In thus imposing your way of worship upon others, you follow the worst of patterns,
Nebuchadnezzar king of Babylon, etc.

[.numbered]
--"`3. In forcing people to your way of worship, who have no belief that it is the right,
you cause them to sin; for whatsoever is not of faith is sin.

[.numbered]
--"`4. In forcing people to your way of worship,
who have a firm persuasion and belief that it is not the right,
you make men hypocrites and time-servers.

[.numbered]
--"`5. By obtruding and enforcing your religion upon others,
you greatly disparage and undervalue it,
and give men the more ground to suspect and dislike it.

[.numbered]
--"`6. You break that great command, which Christ says is the law and the prophets, viz:
'`All things whatsoever ye would that men should do to you, do ye even so to them.`'

"`In conclusion, he makes the following energetic appeal to persecutors,
founded on the well known character and conduct of the persecuted:

"`Ye have known us long; ye have had large experience of us; ye have tried us many ways,
and proved us after divers manners.
And what evil can you convict us of to this day?
Have we not always been a quiet, peaceable, harmless people?
When, being reviled, did we revile?
or when, being persecuted, did we not patiently suffer it?
Ah! what do you propose to yourselves?
Do you think to root us out, and destroy God`'s heritage?
It is impossible.
The root of Jesse bears us; and upon the immovable rock are we immovably built.
O, dash not yourselves against it!
But if you could destroy or ruin persons,
yet is it possible that there can lodge in English breasts,
such more than barbarous inhumanity, to destroy so many thousand families!
The Rome-rid French and Irish have gone far that way;
but English hands were never so defiled.
God grant they never may!
Do you think, by rigorous and cruel usage, to frighten us out of our religion,
and force us to desert our principles?
How can you hope to accomplish such a thing, who have seen our unmoved constancy,
and steadfast perseverance therein,
under all the sufferings that have hitherto been inflicted on us.

"`Have not many of us been already stript of all their outward substance?
not a bed being left them to lie on--not a stool to sit on--not a dish to eat from?
Is there a prison in the nation, or a dungeon in a prison,
which has not been a witness of our groanings?
Have we not been tried by banishment, and proved by death itself?
death in New England, by the hand of the hangman!--death in Old England,
by the rough hands of rude and boisterous officers and soldiers,
who have given divers of our friends those blows,
which in few days have brought them to their graves!

"`I might add to these, burning in the forehead--cutting off ears--unmerciful beatings,
whippings, and cruel scourgings.
But did any, or all of these deter us from the worship of our God?
Nay! hath not our cheerfully undergoing all these hardships,
sufficiently evinced to the world,
that our religion and consciences are dearer to us than our estates, our liberties,
our limbs, or our lives?
Why then will you repeat severities upon us,
which have so often been tried before in vain?
Can you take pleasure in putting others to pain,
and delight yourselves in afflicting others?
O,
suffer not your nature so far to degenerate from the
gentleness and tenderness of true and generous Englishmen!

"`And think not the worse of us, for our faithfulness to our God!
He that is true to God, will be true to men also;
but he that is false and treacherous to God, how is it likely he should be true to men?
endeavour not, therefore, to draw us into unfaithfulness to our God; for that,
to be sure, would be hurtful to us, and no ways advantageous to you.
Neither be ye exasperated against us,
from the difficulty you find in breaking our meetings; or because that,
when you have dragged us out of our meetings, and fined or imprisoned us for being there,
you find us there again: but rather take it for an argument,
that we sincerely love and believe our religion;
and that we find our meetings worth suffering for.
For, indeed, in our meetings we do meet with the Lord our God,
'`in whose presence is fulness of joy.`'`"

--

About the year 1685, William Rogers made another attack upon the Society,
directed in particular against George Whitehead; who, as well as Thomas Ellwood,
had several years before been engaged in controversy with him,
in reply to his Christian Quaker Distinguished.

Rogers`' present production was styled A Rhyming Scourge for George Whitehead,
who probably not thinking himself qualified to meet his adversary with a rhyming reply,
Thomas Ellwood undertook the defence of his friend, by a publication entitled,
[.book-title]#Rogero Mastix--A Rod For William Rogers, In Return For His Rhyming Scourge#.

[.small-break]
'''

In the early part of the succeeding year, 1686,
Thomas Ellwood published a general Epistle to Friends, in which he endeavoured,
with affectionate earnestness,
to check the tendency to division and declension
which had then manifested itself in the Society;
exhorting his fellow members to maintain a true consistency of conduct,
and to guard against the injurious effects of a worldly spirit, as follows, viz:

[.embedded-content-document.epistle]
--

Dear friends, unto whom the gathering arm of the Lord hath reached, and who have known,
in your several measures, a being gathered thereby into the heavenly life,
and are witnesses of the preserving power,
by which you have been kept faithful to the Lord, and regardful of his honour: unto you,
in an especial manner, is the salutation of my true and tender love in the Lord;
and for you, as for myself, are the breathings and fervent desires of my soul offered up,
in the one Spirit, unto him who is your God and mine,
that both you and I may be forever kept in the fresh sense of
his tender mercies and great loving-kindness unto us,
that therein our souls may cleave firmly unto him, and never depart from him.
For, friends, it is a trying day, a day of great difficulty and danger,
wherein the enemy is at work, and very busy, setting his snares on every side,
and spreading his temptations on every hand; and some, alas! have entered thereinto,
and are caught and held therein, for whom my soul in secret mourns.

And truly, friends, a great weight hath been upon my spirit for many days,
and my mind hath been deeply exercised,
in the sense I have of the enemy`'s prevailing by one bait or other,
to unsettle the minds of some, unto whom the arm of the Lord had reached,
and in some measure gathered to a resting place: but not abiding in that pure light,
by which they were at first visited, and to which they were at first turned,
the understanding hath been veiled again; the eye, which was once in some measure opened,
hath the God of this world insensibly blinded again, and darkness is come over them,
to that degree, that they can now contentedly take up again,
what in the day of their convincement, and in the time of their true tenderness,
they cast off as a burden too heavy to be borne.
O my friends! this hath been the enemy`'s work;
therefore it greatly behooves all to watch against him:
for it hath been for want of watchfulness, that he hath got entrance into any.
For, when the mind hath been from off the true watch, in a secure and careless state,
then hath he secretly wrought, and presented his fair baits,
his allurements or enticements by pleasure or profit, to catch the unwary mind.
And hence it hath come to pass, that some, who have come out fairly, and begun well,
and have seemed in good earnest to set their hands to God`'s plough, have looked back,
and been weary of the yoke of Christ,
and have either lusted after the flesh-pots of Egypt again,
or turned aside into some by-path or crooked way in the wilderness,
and thereby fallen short of the promised good land.

But you, my dear friends, in whom the word of life abides,
and who abide in the virtue and savour thereof, ye know the wiles of the enemy,
and the power which subdues him, and the Rock in which the preservation and safety is.
So that I write not these things unto you, because ye know them not;
but the end of my thus writing is,
to stir up the pure mind in all upon whom the name of the Lord is called,
that we all may be provoked to watchfulness against the workings of the wicked one.
Therefore, dear friends, bear, I beseech you, the word of exhortation,
though from one that is little and low, and through mercy sensible of it,
and who hath not been accustomed to appear after this manner; but the wind, ye know,
bloweth where it listeth.

Friends, call to mind the former times, and remember the days that are past and gone,
when the day of the Lord first dawned unto you, and his power seized upon you.
Ye know how weighty and retired the spirits of Friends then were;
how grave and solid their deportment and carriage; how few and savoury their words,
tending to edify the hearers; how great a fear and backwardness was in them,
to enter into familiarity with the world`'s people.
O friends! that was a good day, and that was a safe state; for fear begets watchfulness,
and watchfulness is a means to prevent danger.
Therefore, all friends, keep in the holy fear, and therein watch against the enemy,
that he entangle you not, nor hurt your spirits by a too near familiarity,
and intimate conversing with the people of the world; for therein, I assure you,
lies a snare.

For though it be both lawful and necessary,
and in some cases also useful and serviceable to the Truth,
to converse with them that are without;
yet if any friend should adventure in a frank and free mind,
beyond the limits of the pure fear, to entertain familiarity with the world`'s people,
the spirit of the world in them will seek an entrance; and,
if not diligently watched against, will also get an entrance,
and bring a hurt and a loss upon him or them into whom it so gets.
For being once entered, it will insensibly work,
and dispose the mind to a condescension to and compliance with
the people of the world it converses with,
first in one thing, then in another; in words, in behaviour, etc.,
little things in appearance, but great in consequence,
till at length an indifferency gets up in the mind,
and the testimony of truth by degrees is let fall.
But while the pure fear is kept to and dwelt in, the watch is always set,
the spirit is retired and weighty, and an holy awfulness rests upon the mind,
which renders such converse both safe to the friends,
and more serviceable to them they converse withal.

And, friends, not only in your conversing with the world`'s people,
but in all your conversation and course of life, watch against the spirit of the world;
for it lies near to tempt, and to draw out the mind,
and to lead back into the world again.
You know, friends, that at the first, when the visiting arm of the Lord reached to us,
he led us out of the world`'s ways, manners, customs, and fashions; and a close testimony,
both in word and practice, was borne against them.
But how hath this testimony been kept up, and kept to,
by all who have since made profession of the Truth!
Ah! how hath the enemy, for want of watchfulness, stolen in upon too many,
and led out their minds from that which did at first convince them,
into a liberty beyond the cross of Christ Jesus! and in
that liberty they have run into the world`'s fashions,
which the worldly spirit continually invents to feed the vain and airy minds withal,
that they may not come to gravity and solidity.

Thence it hath come to pass, that there is scarcely a new fashion come up,
or a fantastic cut invented, but some one or other, that professes Truth,
is ready with the foremost to run into it.
Ah, friends! the world sees this, and smiles, and points the finger at it.
And this is both a hurt to the particular, and a reproach to the general.
Therefore, O! let the lot be cast; let search be made by every one,
and let every one examine himself, that this Achan, with his Babylonish garment,
may be found and cast out; for indeed he is a troubler of Israel.

And all friends, who upon true search shall find yourselves concerned in this particular,
I warn and exhort you all, return to that which at first convinced you;
to that keep close, in that abide, that therein ye may know, as at the first,
not only a bridle to the tongue, but a curb to the roving mind,
a restraint to the wandering desire.
For assuredly, friends, if truth be kept to,
none will need to learn of the world what to wear, what to put on,
or how to shape and fashion their garments;
but Truth will teach all how best to answer the end of clothing,
both for useful service and modest decency.
And the cross of Christ will be a yoke to the unruly will,
and a restraint upon the wanton mind;
and will crucify that nature that delights in finery and in bravery of apparel,
in which the true adorning doth not stand, but in the hidden man of the heart,
in that which is not corruptible, even a meek and quiet spirit.

And the grace of God, which hath appeared to all,
and which hath brought salvation to many,
will not only teach to deny all ungodliness and worldly lusts, and to live soberly,
righteously, and godly in this present world, but will also lead those that obey it,
out of all excess, and out of all superfluities and worldly vanities,
and will teach them to order their conversation aright.
Therefore to this heavenly grace let every mind be turned, and therein stayed;
that thereby all who profess the Truth may be kept in the holy limits of it;
that in their whole conversation and course of life--in eating, in drinking,
in putting on apparel, and in whatsoever else we do or take in hand,
all may be done to the glory of God,
that our moderation in all things may appear unto all men.

And let not any deceive and hurt themselves with a false plea,
saying, '`I will be left to my liberty; I have freedom to do, go, or wear so and so;
and religion stands not in clothes,`' etc.,
for that liberty which the worldly spirits leads into, is not indeed the true liberty,
but is a false and feigned liberty, which leads into true and real bondage.
And though religion stands not simply in clothes;
yet true religion stands in that which sets a bound and
limit to the mind with respect to clothes,
as well as to other things.
So that where there is a running out into excess and vanity in apparel,
that is a certain indication and token that the mind is got loose,
and hath cast off the yoke,
and is broken away from its due subjection to that divine power,
in which the true religion stands.

Great hath been the hurt which the enemy hath done in this day,
by leading into a false freedom, and crying up a wrong liberty;
for under this pretence have crept in great disorders, some running out one way,
and some another; some mixing in marriages with the world`'s people,
and some going to the priest to be married.
And many loose and unclean spirits have shrouded themselves
under this plausible pretence of being left to their liberty,
unto whom Truth`'s order is irksome and uneasy; and they kick against it,
and call it imposition, because it checks their licentious liberty.

Therefore all, who join with their plea,
examine and try what liberty it is ye claim and stand for;
for the true liberty is not inconsistent with the cross of Christ,
nor repugnant to his yoke, but agrees with it, and is obtained through it,
and maintained by it.
And none whom the Son hath made free indeed, will or can plead,
or make use of that liberty,
in opposition to any means which the God of order hath appointed,
or set up in his church for keeping out confusion, disorder, and looseness.
And hereby all may take a right measure,
and may certainly know what kind of liberty that is,
which some have so hotly contended for,
in opposition to that necessary and commendable order which God hath led his people into,
and which the enemy, in his agents, labours so hard to lead them out of.
For the enemy well knows, that the tendency and service thereof,
is to detect and discover his secret workings,
and to bring his deeds to light and judgment;
and therefore he strives with might and main to overturn it,
crying out through his instruments; '`Away with your order;
let every one be left to his liberty.`'
By which seemingly fair and specious plea, not only the loose, disorderly,
factious spirits have been let up, and encouraged to greater boldness and licentiousness;
but some simple and well-meaning friends also, not seeing the design of Satan therein,
have been misled thereby, and made use of by the enemy,
and the more subtle of his instruments, to oppose the good order of Truth.

Thus hath the enemy wrought, and sought to lay waste the work of the Lord.
But the Lord, magnified be his holy name, hath not been wanting to his people,
who in sincerity of heart have diligently waited on Him, and trusted in him;
for he hath all along raised up some, whose eyes he hath opened,
to see the design and working of the evil one,
and whose spirits he hath engaged to stand up in a faithful testimony against him,
contending for the way of Truth.
Which when they, in whom the enemy wrought, perceived,
and found they could not run over the heads of Friends,
and carry things on as themselves pleased, they set themselves in a heady, willful spirit,
to raise disturbances in meetings for business, by encouraging and abetting such heady,
loose, contentious, and disorderly persons as would join with them;
thus hardening themselves,
and provoking the Lord to give them up to blindness and hardness of heart,
till at length the enemy prevailed so far upon them, as to work them, by degrees,
from discontent to prejudice, then to enmity, and so at length, in divers places,
to an open defection, apostasy, and separation.

Now, although I know, my dear friends,
that ye who have kept your habitation in the light of the Lord,
and whose eye is single therein, have a clear sight and understanding,
that the spirit which hath thus wrought and fought against the Truth, is not,
nor can be of God, but is of the wicked one;
and although the fruits it hath brought forth,
through the agents and instruments in and by which it hath wrought,
in making disturbances in meetings, to the breaking the church`'s peace;
causing divisions among Friends; publishing to the world most wicked, malicious, railing,
and scandalous books against Friends;
(an effect of the greatest enmity;) shutting and
keeping Friends out of their common meeting-houses,
in which they have a just right and property, and not suffering them to meet therein,
which is a part of the persecution inflicted on Friends by the world,
and at length also setting up separate meetings,
in opposition to the meetings of God`'s people;--although, I say,
these fruits are sufficient of themselves to discover and manifest, to an unclouded mind,
what spirit that is and must needs be, which hath brought them forth;
yet inasmuch as some, partly through weakness of judgment,
and partly through personal affection to some of those leading separatists,
are yet in danger to be betrayed by their fair words and feigned speeches,
wherewith they lie in wait to deceive; I feel a concern remain upon my spirit,
in the love of God, to warn all such, that they join not with,
nor give countenance unto that spirit, that hath thus wrought against the Lord,
and against his people.

For, friends,
in the holy fear of the living God and in the openings
of the spring of his pure life in my soul at this time,
and from the certain knowledge and clear demonstration
which I have received from him therein,
I testify and declare unto you, that this spirit, which in this day hath run out,
and hath drawn out some into opposition against the way and work of the Lord,
into division and separation from the people of the Lord,
and from the holy assemblies which the Lord hath gathered,
and by his powerful presence hath owned, and daily doth own;--this spirit, I say,
is the same with that which formerly wrought, in other appearances,
against the Truth in our time; and is the same with that spirit,
which wrought against the work of the Lord in the days of the holy apostles.
This mystery of iniquity then wrought, and caused many to turn aside,
and to leave the right way of the Lord, and to forsake the assemblies of God`'s people;
yea, and to run into separation too; upon whom the Holy Ghost hath set his brand,
that they were sensual, having not the Spirit.
And many close and sharp testimonies did the Lord give forth
through his servants in that day against this spirit,
and against those that were joined to it, and acted by it,
as may be seen in the Holy Scriptures.

Yea, friends, this spirit that hath led some now to set up their separate meetings,
is the same that led Jeroboam, the son of Nebat, to set up his separate altar at Bethel,
of which you may read, 1 Kings, 12th and 13th chapters.
He was afraid that if the people should continue to go up to the house of the Lord,
to do sacrifice there, as they had been accustomed to do, and as the Lord had required,
they would then forsake him, and return to the Lord again.

O friends! consider,
how hath dryness and withering come upon many a great and stout one in this day,
who have lifted up themselves against the Lord, and have sought,
by the devices of their own hearts, to establish themselves in their own way,
against the way of the Lord, so that the hand they have put forth in that work,
they could not pull in again.

O friends! stand in the fear and counsel of the Lord, and in the dominion of his power,
over this wicked spirit in all its twistings and twinings.
Let neither the frowns nor the fawnings, the threats nor the flatteries,
the hard speeches, nor the oily words, the Pharisaical friendship, the dissembling love,
the seeming kindness, the familiar carriage, the free entertainment,
the offer of advantage, etc., have any influence upon you,
to draw you in the least measure to join or touch with God`'s enemy;
with him that sets up a separate altar, a separate meeting in opposition to,
and to draw or keep from, the right way of the Lord.
Mind well the answer which the man of God gave to Jeroboam`'s tempting invitation;
'`If,`' said he, '`thou wilt give me half thine house, I will not go in with thee;
neither will I eat bread nor drink water in this place.`'
This was where the separate altar was set up.

Therefore, all friends, watch against every temptation thereunto, as you love your lives,
as you regard the good and eternal welfare of your souls;
and let not the name or person of any man have power over you, to draw you aside,
neither let numbers sway with you: in which, I know,
these adversaries of truth do not a little boast, though blessed be God,
with little reason;
but remember that Jeroboam of old had ten tribes
out of twelve to cry up his separate altar;
notwithstanding which, he is branded to posterity in the holy record with this brand,
'`Jeroboam, the son of Nebat, who made Israel to sin.`'
Therefore let not any follow a multitude to do evil. Ex. 23:2.
But all follow that which is good, both among yourselves, and to all men. 1 Thess. 5:15.
For friends, you know whither the broad way leads,
and what it is the wide gate opens into, which the many go in at;
but keep ye to the strait gate, and walk ye on in the narrow way, for in it is safety,
and at the end of it everlasting happiness.

But, friends, because of the straitness of this gate, and the narrowness of this way,
some that have attempted to walk in it, are grown weary of it,
and have sought out another way, which, Jeroboam-like,
they have devised of their own hearts, wherein they may have more room, more scope,
more company, ease in the flesh, liberty to the flesh, and all without control.
And this, I am satisfied, hath not been the least motive to the separation in this day,
as it was the greatest in days past; though some that have been drawn into it,
may not perhaps see the ground upon which it was undertaken.
But the Lord hath opened an eye in many, which sees the rise and ground,
entrance and end, of this libertine spirit and its work.
And this eye will the Lord daily open more and more,
in all that diligently and in sincerity wait upon him.

Therefore all friends everywhere, who have not yet a clear sight,
and a thorough understanding of the nature and work,
design and drift of this dividing spirit, wait I beseech you,
in simplicity of heart and lowliness of mind, upon the Lord,
and keep to the measure of the grace you have received from him;
and suffer not your minds to be swayed or biassed by any personal kindness,
natural affection, relation, kindred, or acquaintance,
but stand single and open to the Lord, not joining to,
nor any way countenancing that which the testimony of Truth,
in the arisings of the heavenly life,
and breakings forth of the divine power through any, goes forth against.
So will your present standing be safe,
and you be preserved out of the snares of this insinuating and treacherous spirit:
and the Lord, in his appointed time, as ye abide with him,
will open your understandings further,
and give you a clearer sight of that which at present you do not fully see,
and thereby bring you to that certainty and assurance, which blessed be his name,
he hath brought many unto.

And you, my dear friends, whose spirits the Lord hath stirred up,
and whose hearts he hath engaged in a holy zeal,
to stand up for his blessed Name and Truth,
and to bear a faithful testimony against this wicked rending spirit,
go on in the strength and power of the Lord, in the might of the God of Jacob;
for you are assuredly on the Lord`'s side, and the Lord Jehovah, the strength of Israel,
is on your side.
Therefore, friends, be encouraged in the Lord, to stand steadfast in your testimony,
not giving way to the enemy, no, not for a moment.
And take heed, I beseech you, in the love of God,
how ye enter into any treaty of peace or terms of agreement with this ungodly,
treacherous spirit, which is out of the truth, and draws out of the truth,
and fights against the truth; for there is no peace unto it, saith my God.

And they who have joined themselves unto it,
and have wickedly given themselves up to be acted by it, and to act for it,
must pass through the river of judgment, if ever they be redeemed from under its power.
Friends, condemnation must first be felt and owned, before reconciliation can be known;
and the fire of the Lord must pass upon the transgressor,
to consume the works of darkness, the ungodly deeds, the envious, reviling speeches,
the wicked, malicious, slanderous books and pamphlets, etc.,
and to burn up the ground from whence they sprang.
For a flaming sword hath the Lord God set in his Eden, which turneth every way;
and none that are gone out can ever come in again,
but they must pass under the flaming edge thereof.
Therefore, my dear friends, stand your ground in the authority of the heavenly life,
and tamper not with God`'s enemies.
Remember the word of the Lord to the prophet: '`Let them return unto thee,
but return not thou unto them.`'
And then what follows?
'`I will make thee unto this people a fenced brazen wall,
and they shall fight against thee, but they shall not prevail against thee;
for I am with thee, to save thee, and to deliver thee, saith the Lord.`'

So the God of life fill your hearts daily more and more
with a Phineas`' zeal for the honour of his name,
and furnish you abundantly with wisdom and counsel, with boldness and courage,
with strength and power, to encounter and overcome the enemy;
and make every one more watchful against the spirit of the world,
to withstand it in all its allurements to vanity, of whatsoever kind;
that whatsoever would defile the camp of the Lord, may be purged out, and kept out,
that the Lord may more and more delight in his people,
and shower down his blessings upon them;
which is the fervent desire of your faithful friend in
the love and service of the unchangeable truth,

[.signed-section-signature]
Thomas Ellwood.

[.signed-section-context-close]
The 24th of the Second month, 1686.

--

We find no account of Thomas Ellwood`'s employment during the four following years,
except that some part of the retirement and leisure
which that period appears to have afforded him,
was occupied in the composition of the first three books of his [.book-title]#Davideis#.
"`But then,`" says Joseph Wyeth, "`the Prince of Orange landing,
and the revolution following, the nation being in arms against king James,
the noise of guns, and sound of drums, etc., so disturbed his meditation and gentle muse,
that his poetical genius left him for a time,
and he thereupon left his work for above twenty years.`"

About the year 1689, two members of the Society at Wiccomb,
John Raunce and Charles Harris, created some dissension and separation,
and published a memorial stating the grounds of their dissatisfaction;
to which Thomas Ellwood replied; and, in 1693,
he wrote a paper in order to defend his reply,
and to exonerate himself from the charge of misrepresentation,
of which he had been accused by his opponents.
In the year 1691 also,
his pen was employed in counteracting a similar spirit of dissension in another quarter,
which had produced an attack upon a work published by William Penn, in 1681, entitled,
A brief examination and state of Liberty Spiritual, etc.

About the same time,
Thomas Ellwood was occupied in transcribing and preparing for the press,
the [.book-title]#Journal of George Fox#, who died in the 11th month, 1690.
To this he also prefixed a brief,
but comprehensive review of the character of his excellent and lamented friend;
the insertion of which will probably not be unacceptable to the reader.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Ellwood`'s account of that eminent and honourable servant of the Lord, George Fox.

This holy man was raised up by God, in an extraordinary manner,
for an extraordinary work, even to awaken the sleeping world,
by proclaiming the mighty day of the Lord to the nations,
and publishing again the everlasting Gospel to the inhabitants of the earth,
after the long and dismal night of apostasy and darkness.
For this work the Lord began to prepare him,
by many and various trials and exercises from his very childhood:
and having fitted and furnished him for it, he called him into it very young;
and made him instrumental, by the effectual working of the Holy Ghost,
through his ministry to call many others into the same work,
and to turn many thousands from darkness to the light of Christ,
and from the power of Satan unto God.

I knew him not until the year 1660;
from that time to the time of his death I knew him well, conversed with him often,
observed him much, loved him dearly, and honoured him truly;
and upon good experience can say, he was indeed a heavenly-minded man,
zealous for the name of the Lord, and preferred the honour of God before all things.

He was valiant for the Truth, bold in asserting it, patient in suffering for it,
unwearied in labouring in it, steady in his testimony to it, immoveable as a rock.
Deep he was in divine knowledge, clear in opening heavenly mysteries,
plain and powerful in preaching, fervent in prayer.
He was richly endued with heavenly wisdom, quick in discerning, sound in judgment,
able and ready in giving, discreet in keeping, counsel; a lover of righteousness,
an encourager of virtue, justice, temperance, meekness, purity, chastity, modesty,
humility, charity, and self-denial in all, both by word and example.
Graceful he was in countenance, manly in personage, grave in gesture,
courteous in conversation, weighty in communication, instructive in discourse,
free from affectation in speech or carriage.
A severe reprover of hard and obstinate sinners,
a mild and gentle admonisher of such as were tender, and sensible of their failings.
Not apt to resent personal wrongs; easy to forgive injuries;
but zealously earnest where the honour of God,
the prosperity of truth and the peace of the church, were concerned.
Very tender, compassionate,
and pitiful he was to all that were under any sort of affliction; full of brotherly love,
full of fatherly care: for indeed the care of the churches of Christ was daily upon him,
the prosperity and peace whereof he studiously sought.

Beloved he was of God; beloved of God`'s people; and,
which was not the least part of his honour, the common butt of all apostates`' envy;
whose good, notwithstanding, he earnestly sought.

He lived to see the desire of his soul,
the spreading of that blessed principle of divine light,
through many of the European nations,
and not a few of the American islands and provinces,
and the gathering of many thousands into an establishment therein:
of which the Lord vouchsafed him the honour to be the first effectual publisher,
in this latter age of the world.
And having fought a good fight, finished his course, and kept the faith,
his righteous soul, freed from the earthly tabernacle,
in which he had led an exemplary life of holiness,
was translated into those heavenly mansions,
where Christ our Lord went to prepare a place for his +++[+++own];
there to possess that glorious crown of righteousness which is laid up for,
and shall be given by the Lord, the righteous Judge,
to all them that love his appearance.
Ages to come, and people yet unborn, shall call him blessed;
and bless the Lord for raising him up: and blessed shall we also be,
if we so walk as we had him for an example; for whom this testimony lives in my heart,
he lived and died the servant of the Lord.

[.signed-section-signature]
Thomas Ellwood

--

In the year 1694, Thomas Ellwood engaged in controversy with George Keith;
whose separation from his friends, and renunciation of those principles, of which,
during a period of about thirty years, he had been a public and zealous advocate,
became a source of much and painful dissension in the Society,
as well as of heartfelt sorrow to those with whom he had, at one time,
appeared to be cordially united in Christian fellowship.

George Keith was educated in the Presbyterian church, was a man of talent and learning,
and had obtained the degree of Master of Arts in the university of Aberdeen,
the place of his nativity.

The first mention we find of him,
after he became a member and minister of the Society of Friends,
is in Sewel`'s account of the dispute to which Thomas Ellwood alludes in his journal,
held in London in the year 1674, between some Baptists and Friends,
and in which the cause of the latter was supported by George Whitehead, Stephen Crisp,
William Penn, and George Keith.
In the succeeding year,
he united with Robert Barclay in a similar engagement
with some scholars of the university of Aberdeen;
on which occasion four of the students were induced to embrace Friends`' principles.

In 1677, George Keith united with George Fox, William Penn, Robert Barclay,
and other Friends, in their religious labours in Holland and Germany; and,
some years afterwards, he became one of the earliest settlers in Pennsylvania.

After residing there about ten years, he was the means of aggravating,
by a religious schism,
the political differences which then agitated that infant settlement.
Ambitious of rising to influence and importance in the Society,
and obtaining a superiority over his brethren,--and
having imbibed notions subversive of social order,
they led him to conduct himself with great disrespect
towards the civil authorities in the state,
and rendered him dissatisfied with the restraint which
the excellent discipline established in the Society,
imposes upon its members.

He also opposed and ridiculed some of the doctrines and practices of the Society; and,
having formed a separate congregation,
distinguished himself and his adherents by the denomination of "`Christian Quakers.`"
He asserted, however,
that his dissatisfaction was not with the body of Friends generally,
but only with some unsound members in Pennsylvania; and accordingly he returned, in 1694,
for the purpose of pleading his cause before the yearly meeting in London.
After the meeting had concluded its routine of business,
adjournments were continued for several days,
in which a full opportunity was afforded to Keith and his party,
of stating their grievances,
and the utmost endeavours were used to effect a
reconciliation between him and his friends;
but so little disposition did he evince toward such a step,
that the means employed to close the breach, tended only to widen it,
and were followed by his total separation from the Society.

Thomas Ellwood,
anxious to counteract the calamitous effects of
a disposition to break the bonds of union,
and cast off the restraints of social order, wrote "`An epistle to Friends,
briefly commemorating the gracious dealings of the Lord with them,
and warning them to beware of that spirit of contention and
division which hath appeared of late in George Keith.`"

The following is an extract from his introductory observations.

[.embedded-content-document.letter]
--

[.salutation]
Dear friends,

Whom the Lord hath called with an holy calling, and who,
through faithfulness to the heavenly call, are become the chosen of the Lord.
It is in my heart, in the openings of the love of God, to send these few lines among you,
as a salutation of true and hearty love unto you;
and in the tendering sense of the Lord`'s unspeakable goodness unto us,
which at this time rests with an affecting weight upon my spirit,
briefly to commemorate the gracious dealings of
the Lord with us since we have been a people.

Great and manifold have been the mercies of our God unto his people, in this his day;
and his loving-kindnesses are beyond expressing: when we were young and little,
his fatherly care was over us; he preserved us and nourished us,
and caused us to grow up before him.
How did he carry his lambs in his bosom, when the beasts of prey roared on every side,
seeking to devour!
Who can rehearse the many deliverances He hath wrought for his people,
in their passage from spiritual Egypt!
How hath he girded their loins with strength,
and covered their heads in the day of battle!
How hath he subdued their enemies before them, and put to flight the armies of aliens!
How hath he fed them with bread from heaven, and made them to suck honey out of the rock!
Yea, he hath caused the rock to give forth water abundantly,
and hath been to his people as a brook in the way and
the shadow of a mighty rock in a weary land.
So that from a sensible experience we can say, to his praise, our bread hath been sure,
and our water hath not failed, as we have singly relied on him.

O! his goodness is unutterable,
and his faithfulness hath never failed them that trust in him.
When have we ever been in prison for his sake,
and He hath not visited and comforted us there?
What sufferings have any undergone on his account,
and he hath not abundantly recompensed the loss?
Nay, hath he not often stopped the mouths of lions,
and reproved rulers for the sake of his people, saying, '`touch not mine anointed,
and do my prophets no harm.`'
In all our exercises he hath been with us, and he hath stood by us in our sorest trials;
yea, he hath caused his angel to encamp round about us,
so that no weapon formed against us hath prospered;
but every tongue that hath risen up against us, the Lord hath given us power to condemn:
blessed be his holy name; and exalted and magnified be his glorious power forever!

These things, and much more than I can write, I doubt not but ye, my dear friends,
are witnesses of; ye especially, my elder brethren,
who were called early in the morning of this day,
and have stood faithful in your testimony until now,
who from your own both early and late experiences can set your seals to the truth hereof;
and unto you I do believe this brief commemoration of the
goodness and loving-kindness of the Lord to his people,
will be pleasing and delightful,
as I hope it may prove useful and profitable unto us all,
in the stirring up of the pure mind,
and putting us in fresh remembrance of the Lord`'s manifold favours towards us,
and gracious dealings with us;
which should be as a renewed engagement upon us to cleave fast unto the Lord, and,
in humility of heart, to walk closely with him, both that we may, as far as in us lies,
answer his great loving-kindness to us-ward,
and receive from him daily strength and ability to stand,
and withstand the assaults and temptations of the enemy, and escape his snares,
wherewith he is, at this time, as busy and industrious to betray,
and draw aside from the simplicity of the truth, as ever he was.

For, friends, ye know we have a restless adversary to watch against, and to war with;
one that sometimes walks about as a roaring lion, seeking whom he may devour;
and sometimes creeps about as a subtle serpent, seeking whom he may betray;
whom in each appearance, it is our duty and interest to resist,
steadfast in the faith which overcomes.
I need not recount unto you, my friends, the many winds and floods, storms and tempests,
of open and cruel persecutions, which this roaring adversary hath often raised,
and caused to beat upon us, to have driven us, if possible, from off our foundation;
ye cannot have forgotten it, nor that noble arm of the Lord,
which was made bare for our preservation; and,
by preserving us against the most furious shocks, gave evidence even to the world,
that we are that people whose house is founded and built upon that immovable rock,
Christ Jesus.

At this sort of fighting the enemy hath been foiled; which hath made him shift his hand,
and, like a cunning hunter, spread his nets, set his snares, lay his baits,
to catch the simple and unwary ones.
Thus wrought this subtle enemy in the early times of Christianity,
sometimes stirring up the rulers, both Jews and Gentiles,
to fall with violent and bloody hands upon the little flock of Christ and sometimes,
in the intermissions of those storms,
covering his hooks with the taking baits of pleasure, profit and preferment,
he catched some,
perhaps of those that had withstood the strongest storm of outward persecution,
and made them instruments for himself to work by to betray others.
Such was Diotrephes of old, whose aspiring mind, loving and seeking preeminence,
laboured to make a schism in the church,
prating against even the elders thereof with malicious words, etc.
What mischief the wicked one hath wrought in our day by such ambitious spirits,
I need not recount, nor is it pleasing to me to remember: ye know it, to your grief,
as well as I. But this in all such cases is observable,
that such as have made disturbances in the church,
and have run into divisions and separations from friends,
have framed to themselves some specious pretence or other,
as the inducement to their undertaking, which they have industriously spread abroad,
and varnished over with the fairest colours they could,
to allure and draw others to join with them.

--

This publication excited the resentment of George Keith, who,
after having in vain demanded its suppression by the Society,
opposed it with what he styled "`A Loving Epistle;`" in
which he charged the author with fifty perversions;
and in a short time after he brought forward what he called proofs of those perversions,
and at the same time expressed his unalterable attachment to the Society.
This was speedily followed by a rejoinder from Thomas Ellwood,
entitled "`A further discovery of that spirit of contention and division,
which hath appeared of late in George Keith, etc., wherein his cavils are answered,
his falsehood is laid open,
and the guilt and blame of the breach and separation in America, etc.,
are fixed faster on him; written by way of epistle,
and recommended as a further warning to Friends.`"

The subject of George Keith`'s differences was resumed by the yearly meeting in 1695,
and issued in his final separation from the Society,
that body confirming the proceedings against him,
by which he had been disowned in America.
Soon after he published some observations on that decision, etc.,
which again furnished employment for Thomas Ellwood`'s pen,
and were met by his "`Truth Defended,
and the Friends thereof cleared from the false charges, foul reproaches,
and envious cavils, cast upon it and them by George Keith, an apostate from them,
in two books by him lately published;
one called '`A true Copy of a Paper delivered into the yearly meeting,`' etc.;
the other the pretended '`Yearly meeting`'s nameless Bull of Excommunication.`'

George Keith retained for a short time some adherents,
consisting of persons who had separated from the Society;
and after being deserted by them, formed a congregation who met in Turner`'s hall,
Philpot lane, London, and were for some time very numerous;
but declined on his manifesting an inclination to join the established church.
Turner`'s hall he also made the theatre of violent declamations
against his late fellow professors and their principles;
and gave public notice of a meeting to be held there in the fourth month, 1696,
"`to discover the Quakers`' errors.`"
Of this meeting he soon after published a narrative,
which was followed by a reply from Thomas Ellwood`'s pen, entitled:
[.book-title]#An Answer to George Keith`'s Narrative of his Proceedings at Turner`'s hall, etc.#,
wherein his charges against divers of the people called Quakers,
in that and another book of his, called Gross Errors, etc., are fairly considered,
examined and refuted.`"

The following quotation will give some idea of the character of the meeting.

[quote]
____
George Keith "`having published many books against us,
and in defence of those books wrangled with us for a while in print,
till he found himself too closely pinched,
to be able to give an answer fit to be seen in print,
hath at length bethought himself of a wile to excuse himself from answering; which was,
to set up a kind of judicial court of his own head, and by his own authority,
in a place at his own command, on a day of his own appointing,
there to charge and try divers of us who are called Quakers, whether present or absent,
concerning matters of faith and doctrine;
and that the rude multitude might not be wanting to his assistance there,
he gave public notice of it some time before, by an advertisement in print,
and therein a sort of summons to some of us by name,
to others by designation to be present.
This arbitrary proceeding, and usurped authority,
as we judged it unreasonable in him to impose, so we did not think fit to submit to,
or own, and therefore forbore to appear at that time and place by him appointed.
Yet, lest any whom he should draw thither, might mistake the cause of our not appearing,
the reasons thereof, drawn up in short heads,
were sent thither to be read and given among the people, which they were.
However,
according to his before declared intention to proceed whether any of us were there or no,
he being judge of his own court, over-ruled our reasons,
and went on to arraign and convict us absent.

The pageantry of this day`'s work, as acted there by himself,
he hath since published with his name to it,
under the title of '`An exact Narrative of the proceedings at Turner`'s hall, etc.,
together with the disputes and speeches there, between George Keith and other Quakers,
differing from him in some religious principles.`'
How idle is this in him,
to pretend in his title to give an account of disputes
and speeches between him and other Quakers,
whereas his narrative itself gives no account of any dispute there,
nor any thing like it;
and of that little that was said by any of those few Quakers that were present,
most was to the people, tending to show them the unreasonableness of his undertaking,
and desiring them to reserve one ear for the other side.
____

George Keith,
feeling probably some difficulty in openly opposing those
principles of which he had so lately been a zealous defender,
declined again meeting his opponent in __propria persona__,
but found a ready champion in the author of "`The Snake
in the Grass,`" who produced a vindication of his cause,
as far at least as regarded the doctrines in dispute, styled,
"`Satan Disrobed from his disguise of light,
in reply to Thomas Ellwood`'s Answer to George Keith`'s Narrative, 1697.`"
Thomas Ellwood made considerable progress in a reply,
but relinquished the further prosecution of it.

Towards the close of the year 1698, several clergymen of Norfolk,
in consequence of a meeting held by some Friends near the residence of one of them,
which produced an increase of members in that neighbourhood,
challenged the Friends to a public dispute at West Dereham in that county;
the issue of which not being satisfactory to the clerical party,
they endeavoured to avail themselves of more powerful weapons than their arguments,
and accordingly promoted the presentation to parliament,
of two petitions against the Society.
Thomas Ellwood published, early in the following year,
[.book-title]#A Sober Reply on behalf of the People called Quakers, to two Petitions against them,
the one out of Norfolk, and the other from Bury in Suffolk,
being some brief observations upon them.#
The publication of this, with the activity of Friends resident in the metropolis,
in furnishing members with correct information on the subject,
by personal attendance on the house, as well as through the medium of the press,
was attended with the desired effect,
and the efforts of their opponents proved fruitless.

George Keith continued to hold annually a meeting at Turner`'s hall,
for discussing the principles and practices of Friends; and William Penn,
who had recently returned to his province in the New World this year,
became the principal object of his invectives,
which were followed up shortly afterwards by a publication,
of which Keith was the avowed author, entitled,
"`The Deism of William Penn and his brethren, destructive to the Christian religion,
exposed.`"

To this work Thomas Ellwood commenced a reply,
in which he had made considerable progress, when he was induced to relinquish his design,
deeming the necessity of his labour superseded,
by the publication of a Friend of Bristol, entitled, "`Honesty the truest Policy:
showing the sophistry, envy, and perversion of George Keith, in his three books:
viz. his '`Bristol Quakerism,`' '`Bristol Narrative,`' and his '`Deism.`'`"

Though the writings of William Penn contain unanswerable refutations of this calumny,
the following extracts from Thomas Ellwood`'s vindication of
his principles may be acceptable to the reader,
as collateral evidence of the soundness of that distinguished member of our Society,
as well as of his contemporary fellow professors,
in regard to the fundamental doctrines of the gospel.

[.embedded-content-document.paper]
--

Now herein George Keith`'s both injustice and malice are the greater, in charging William Penn,
and his brethren the Quakers, with deism; inasmuch as he assuredly knows,
which some adversaries have not had the like opportunity to know, as he hath had,
by certain experience,
drawn by so many years intimate conversation with William Penn and the Quakers,
in free and familiar conferences, and in reading their books,
that William Penn and the Quakers, both in word and writing, publicly and privately,
have always, and on all occasions, confessed, acknowledged, owned, as well as believed,
the incarnation of Christ, according to the Holy Scriptures,
viz.--That the Word was made flesh.--That when the fulness of time was come,
God sent forth his Son, made of a woman, made under the law,
to redeem them that were under the law.--That Christ Jesus, being in the form of God,
and thinking it no robbery to be equal with God, made himself of no reputation,
and took upon him the form of a servant, and was made in the likeness of men;
and being found in fashion as a man, he humbled himself, and became obedient unto death,
even the death of the cross.
That Christ died for our sins, according to the Scriptures, and that he was buried,
and that he rose again the third day,
according to the Scriptures.--That he was delivered for our offences,
and raised again for our justification.
That he is the propitiation for our sins; and not for ours only,
but for the sins of the whole world.--That he ascended up far above all heavens,
that he might fill all things.--That he is the one Mediator between God and men.
That he is at the right hand of God, and maketh intercession for us;
and is our advocate with the Father.--And that it is He which was ordained of God,
to be the Judge of quick and dead.

These things, I say, George Keith certainly knows have been constantly held, believed,
professed, and owned by William Penn and his brethren the Quakers in general,
both privately and publicly, in word and writing.
These things are so often testified of in our meetings,
and have been so fully and plainly asserted and held forth in our books,
that we might call in almost as many witnesses thereof, as have frequented our meetings,
or attentively read our books.

The book of William Penn`'s, called,
[.book-title]#A Discourse of the General Rule of Faith and
Life,# to which George Keith`'s Deism is an answer,
George Keith tells us in his preface, was first printed in the year 1673,
as an appendix to William Penn`'s part of the Christian Quaker--a folio book in two parts;
the former written by William Penn, the latter by George Whitehead.
In that former part of the Christian Quaker, written by William Penn,
though the tendency of it is to assert and defend the divinity of Christ,
and his spiritual appearance by his divine light in the hearts of men;
yet there is enough said concerning his manhood, his outward appearance,
and his sufferings in the flesh,
to free William Penn from the imputation and suspicion of Deism.

No longer ago than in the year 1692, nineteen years after that book of William Penn`'s, called,
[.book-title]#A Discourse of the general Rule of Faith and Life,# was in print, George Keith,
in his serious Appeal, page 7, says,
'`According to the best knowledge I have of the people called Quakers,
and those most generally owned by them, as preachers and publishers of their faith,
of unquestioned esteem among them, and worthy of double honour, as many such there are,
I know none that are guilty of any such heresies and blasphemies as thou accusest them:
and I think I should know, and do know,
those called Quakers better than C. Mather +++[+++against whom he then wrote]
or any of his brethren; having been conversant with them, in public meetings,
as well as in private discourse, with the most noted and esteemed among them,
for above twenty-eight years past, and that in many places of the world, in Europe,
and for these divers years in America.`'
I say, all this considered, how will George Keith,
upon the charges he now makes against William Penn,
acquit himself from having been a professed deist,
all the while he was among the Quakers`'? Yet he himself well knows, that neither he,
nor William Penn, nor any of the Quakers, ever were deists; ever did deny, disown,
or disbelieve the coming, incarnation, sufferings, and death of Christ,
as man outwardly in the flesh, his resurrection, ascension, and mediatorship;
and he himself has undesignedly acquitted William Penn from his present charge of deism,
by a story he told in his first Narrative, page 38,
that upon some urging him to give an instance of one
English Quaker that he ever heard pray to Christ,
William Penn, being present, said, '`I am an Englishman, and a Quaker;
and I own I have often prayed to Christ Jesus, even him that was crucified.`'`"

--

Before taking leave of George Keith, we may remark,
that his congregation at Turner`'s hall, and his reputation among other dissenters,
gradually declined, on their perceiving a change in his religious tenets,
which soon approximated to those of the establishment; and after having, as we have seen,
relinquished the Presbyterian habiliments,
and successively assumed the garb of Quakerism, and other modes of dissent,
his last transformation exhibits him in the sacerdotal robes of Episcopal Orthodoxy;
in which character he performed, in 1702,
an unsuccessful embassy to the western hemisphere,
with the design of restoring other dissenters to the bosom of the Mother Church.
After his return, he obtained the living of Elburton parish, in Sussex,
where he continued to maintain a violent opposition against Friends,
till near the close of his mortal career, which terminated in 1715.

We find no mention of Thomas Ellwood for some years after his controversy with Keith,
except that in the course of the years 1701 and 1702,
he entered into a correspondence with John Shockling, a clergyman in Kent,
on the subject of Baptism, which was not presented to the public.

This period of relaxation from other engagements,
facilitated his completion of a connected view of Scripture history, digested,
as far as he possessed the means of ascertaining it, in chronological order.
The first part appeared in 1705, under the title of [.book-title]#Sacred History,
or the historical parts of the Holy Scriptures of the Old Testament,
gathered out from the other parts thereof, and digested, as near as well could be,
into due method with respect to order of time and place:
with some observations here and there, tending to illustrate some passages therein.#
The second part, comprising the history of the New Testament, followed in 1709.
This is a work of considerable merit, and has been favourably received by the Society,
as is evinced by the sale of four editions, and the publication of a fifth,
which is still extant, in three duodecimo volumes.

The author does not adhere generally to the words of the sacred Text,
and has availed himself of the observation of biblical critics,
to whose works he had access, particularly the learned Grotius,
in elucidating difficult passages,
or those in which he deemed the authorized version to be erroneous.
The gospel history embraces the discourses of our Lord,
and is preceded by a biographical sketch of the historical writers of the New Testament.

The following quotations,
illustrative of the views with which the pious author engaged in his undertaking, will,
we presume, be acceptable to those who do not possess the work.

[quote]
____
What Cicero saith of history in general, namely, that it is, Temporum testis,
lux veritatis, vita memorice, magistra vitcB, et nuncia antiquitatis; i. e.
The witness of time, the light of truth, the life of memory, the mistress of life,
and the messenger of antiquity, cannot be so well verified of any particular history,
as of that which, being written by divinely inspired penmen,
is contained in the books of the Old and New Testament:
the former of which is the subject of this volume.

Of the matter nothing need be said, nothing perhaps can be said,
to add to the excellency or credit thereof;
but of the motive or inducement to this undertaking, somewhat, peradventure,
may be necessary to be hinted.

Two things more especially led me to it: One, that the divine Providence, the wisdom,
power, goodness, and favour of God, in ordering, disposing, providing for, preserving,
defending,
and wonderfully delivering his servants and people out of the greatest straits,
difficulties, hardships, dangers, and sufferings, being more directly,
and in a continued series and course of actions, set before the reader`'s eye;
he might be thereby the more stirred up and engaged to admire and magnify, to love,
reverence and fear the Lord, and be the more careful not to offend him.

The other motive was, that all, the youth especially, of either sex,
under whatsoever religious denomination they go,
might be furnished with such an entertainment,
as might yield them at once both profit and delight.

For having, not without uneasiness of mind, observed how much too many, not to say most,
mis-spend their precious time; some in reading vain fictions, called romances,
lewd novels, lascivious poems, and vice-promoting play books; others,
more soberly and religiously inclined, in reading other books, if not much hurtful,
yet not much instructive and beneficial, I hoped I should do no unacceptable service,
at least to some, in presenting them with the [.book-title]#Sacred History#, so digested,
as might both invite their attention, and recompense their pains in reading,
with the double advantages of godly instruction and virtuous pleasure.

If any shall think the undertaking needless,
because the history is already extant in the Bible; I entreat such to consider,
that although the Bible be, or may be, in every hand,
and ought to be read by all that can read, with diligence and attention of mind; yet,
since the history lies diffused and scattered throughout the whole book,
it is no small discouragement to the reader,
that is desirous to peruse the history in a regular course,
to find the thread thereof frequently cut off by the interposition of other matters.
____

The biographer of Thomas Ellwood,
in the Supplement which has been usually published with his own memoir,
gives his estimate of this work in the following terms:
"`A work indeed it is both pleasant and profitable;
containing such judicious observations, and witty, though grave,
turns on passages and things, as make it, as well as his other writings,
not only pleasant to read, but profitable to the reader.
A work that will remain a monument of his worth and ingenuity to generations to come.`"

In 1707 Thomas Ellwood closed his controversial labours,
by a work designed to evince the spirituality of the Christian dispensation,
and its abrogation of types and ceremonies, in answer to a recent publication, entitled,
"`A Divine Treatise, written by way of essay, to demonstrate,
according to the Mosaical philosophy, that water baptism, imposition of hands,
and the commemoration of the death and passion of our ever blessed Lord and Saviour,
under the species of bread and wine,
are suitably and homogeneally adapted to the present and imperfect state of nature,
as man consists of body, soul and spirit.`"
His answer was entitled, [.book-title]#The Glorious Brightness of the Gospel Day,
dispelling the shadows of the legal dispensation,
and whatsoever else of human invention hath been super-added thereunto#.

About the same time Thomas Ellwood was involved, with three other friends,
in a suit for tithes, which was attended with much trouble and expense,
from the circumstance of the claimants, instead of distraining by warrant,
having instituted a process in the Court of Exchequer.
This was peculiarly cruel and unchristian with respect to Thomas Ellwood,
the demand against him being only twelve shillings,
for the obtaining of which there was a clear and summary process pointed out by law.

John Penington, one of the three Friends, living in Buckinghamshire,
the attachment obtained would not reach him, the others residing in Hertfordshire.
In consequence the prosecution, as to him, proved null and void.
The claim on Thomas Ellwood and his two other friends,
Abraham Butterfield and William Catch,
amounted to 32 14s. l0d. and the costs to 71
17s. 8d. together 104 12s. 6d. to defray which,
goods were distrained from Thomas Ellwood,
amounting to  24 10s. and from his two fellow sufferers to the amount of 107 16s.
8d. making a total of 132 6s. 8d. which exceeded the original demand by 99 lis.
l0d.

In the year 1710, Thomas Ellwood was engaged in preparing for the press,
an account of Oliver Sansom, of Abingdon, Berkshire,
committed to him during the life of the author,
and to which he prefixed a pertinent testimony respecting him.

The year following, he ushered into the world the last, but not least,
effort of his muse, entitled--[.book-title]#Davideis: the life of David,
king of Israel--A sacred poem,
in five books#; to the composition of which he
had occasionally devoted some leisure hours,
for a considerable number of years, without any view to publication.

In a postscript to his "`Supplement,`" Joseph Wyeth says:
"`I have understood that our friend Thomas Ellwood,
after he had finished and published [.book-title]#Davideis#, signified that
he had but one thing more which lay upon his mind,
and that was, to add something to his journal;
which was chiefly to give an account of his books and writings.`"
His accomplishment of this desire was probably
prevented by the debilitated state of his bodily powers,
in consequence of an asthmatic disorder,
to which he was subject during the last few years of his life:
previously to this affection he appears to have enjoyed, with but little interruption,
that uniform state of good health,
which is the usual attendant of a vigorous constitution,
preserved by moderation and temperance.

On the 23rd of second month, 1713, he was attacked by a paralytic seizure,
which he survived only about a week.
During this time he frequently expressed his love to his friends,
and the pleasure he derived from their company--
his desire for the welfare of the Society,
and especially for that portion of it with which he had
been more immediately connected--and the resignation,
peace, and joy,
which attended his mind in the prospect of a speedy
transition to a never ending state of being.
This took place on the 1st of third month, 1713, in the seventy-fourth year of his age.
His remains were interred at Jordan`'s burying ground,
where they were attended by a large company of his fellow professors,
and many of other persuasions, by whom he appears to have been held in much esteem.
He had suffered the loss of his wife, who occupied the station of a minister,
about five years previous to his decease.
They do not appear to have had any offspring.
Their residence was at Hunger Hill, near Amersham,
where he seems to have led a life of retirement, unencumbered with much, if any,
commercial engagement.

Thomas Ellwood`'s station in the church was that of an elder;
though he did sometimes "`appear as a minister.`"
"`In those meetings set apart for the affairs of
Truth,`" one of his contemporaries remarks,
"`he often appeared in great wisdom,
having an extraordinary talent given of the Lord for that work,
more than many other brethren; and faithful he was in watching for instruction from God,
to improve the same to his glory and the church`'s advantage.`"^
footnote:[Richard Vivers`' Testimony concerning Thomas Ellwood.]
The loss of his valuable services in the exercise of Christian discipline,
was deeply felt by his friends, as is evinced by the testimonies to his worth,
prefixed to his journal.
Joseph Wyeth, in describing his character, says: "`He was a man of a comely aspect,
of a free and generous disposition, of a courteous and affable temper,
and pleasant conversation; a gentleman, a scholar, a true Christian, an eminent author,
a good neighbour, and kind friend.`'

[.asterism]
'''

[.alt.centered]
=== George Bowles`' Testimony Concerning Thomas Ellwood.

[.salutation]
Dear Friends,

It is in my heart on this occasion,
briefly to commemorate the tender dealings of the Lord
with his people in this latter age of the world,
when it hath pleased him, in love to poor lost man, graciously to appear,
by the breaking forth of his glorious gospel-day.
And by the secret divine reaches of the hand of God,
which have been felt and seen in the light of it,
many have been drawn in their spirits to seek after the Lord,
and to inquire after the knowledge of the way of life and salvation.
Blessed be his holy name, who was graciously pleased,
by the inshinings of this divine light in the hearts of many,
to expel the darkness and rend the veil.
Then was the arm of his mighty power made bare,
for the gathering many thousands to the saving knowledge of himself.
In that day was the Lord pleased, according to his promise,
to pour forth of his Spirit upon sons and upon daughters; yea,
upon servants and upon handmaids, and many were made to prophesy.
These being qualified by the Holy Spirit, which they received,
and were baptized by it into his name, became willing,
and were freely given up in obedience to the Lord,
and in bowels of tender love to the souls of mankind,
in his power to preach the gospel of life and salvation to those to whom they were sent,
and many were turned from darkness to light, and from the power of Satan unto God,
by their ministry.
Amongst these, our dear deceased friend and brother, Thomas Ellwood,
was one whose conscience was reached and awakened by
the powerful ministry of dear Edward Burrough.
Of that day and time,
and the worthy instrument by whose ministry he was convinced and turned unto God,
and made sensible of the divine principle of life and light in his own heart,
I have heard him speak with great regard;
and also relate the sufferings which attended him after he received the truth,
in his father`'s family, for the truth`'s sake;
and how the Lord preserved him in that time,
under the various exercises which he passed through for truth`'s testimony.
This, for Christ`'s sake, he was conscientiously concerned to stand in,
according to that plainness and simplicity which truth then led,
and still continues to lead, the sincere disciples of Christ into,
by which they were distinguished from the world; and for the sake thereof,
were despised of men and hated of the world.
Such was the plain language of thou to one, and refusing the hat honour; for which,
dear Thomas Ellwood suffered not a little in that day,
as by the following account of his life, more fully appears.
It were Well, if all who come up in a profession of the blessed truth in this time,
were faithful in these, and in the other branches of its testimony.
Let all consider, that the neglecting thereof, is in degree,
strengthening the hands of evil doers, and making void the sufferings of the faithful,
who for the sake of their testimony, loved not their lives to the death;
but underwent cruel mockings, buffetings, stonings, whippings, stockings, revilings,
imprisonments, and spoiling of goods; rejoicing in the Lord,
that they were counted worthy to suffer for his name-sake.
In this respect, my dear friend was a good example, he being a man of a steady mind,
and very patient in suffering, as well as faithful in his testimony for truth,
and took joyfully the spoiling of his goods,
wherein he was tried but a few years before his death.
He was often engaged in defence of truth`'s testimony, both against professed adversaries,
and also against the libertine spirit which appeared in some,
professing the same truth with us,
who opposed themselves against that good order
and discipline which the truth led Friends into.
This will abundantly appear from the books themselves, which are in print,
written upon various occasions and divers subjects;
and let not his great labour and industry be forgotten,
in writing those two historical volumes relating to the Old and New Testament:
a work truly great, and may be of great use and service.
By his many labours,
it may be perceived that the Lord had endowed him with an excellent gift,
and qualified him for the service of truth, his church and people;
which he employed to the honour of the great Giver,
and to the comfort and edification of the church of Christ.

But more especially were his services known to the brethren in this county of Bucks;
most of whom are fallen asleep, and but few remaining, who knew him in his beginning,
or his first services for the Lord, his church and people;
amongst whom he was a zealous assertor of that excellent
discipline the Lord had opened and led his people into,
for preserving his church as a garden enclosed.
For this cause, many of those libertines set themselves fiercely against him,
and shot their arrows at him; but the Lord defended him,
and covered his head in the day of battle, and his bow abode in strength,
and his bough spread over the wall, and continued fresh and green:
but a blast from the Lord came upon their evil work; and how have they melted away?
How is their strength failed, and their work brought to naught?
But the blessing of the Lord is with his people, even with the faithful, to this day,
whom he hath preserved as a peculiar treasure to himself:
blessed be his holy name forevermore.

It may be truly said of this dear friend, that as the Lord fitted him for his service,
so was he eminently serviceable in his hand, in the church of Christ;
of which there are many living witnesses in this and the adjacent counties.
The sense of which toucheth me and others with the deeper
sense of the great loss the church hath by his removal.
But being also sensible through the Lord`'s goodness, that our loss is his eternal gain,
I feel in my heart an humble submission to the will of Him,
who doeth whatsoever pleaseth him, both in heaven and in earth:
and who shall say unto Him, What doest thou?
It is the tender breathing of my spirit to the God and Father of our Lord Jesus Christ,
that he would be graciously pleased, in pity and compassion to his people, to raise up,
fit and furnish more faithful servants for his work and service,
and make them zealous for his name and truth upon the earth,
that the place of this dear friend,
and other faithful servants of the Lord and his people,
of late removed from amongst us in these parts, may be supplied;
and that the spouse of Christ may, amidst all her tribulations,
afflictions and sore exercises, be made to praise the Lord, and bless his holy name,
who taketh away one, and raiseth up another, and blesseth his children with his goodness,
according to his promise made of old, by the holy prophet, saying,
"`I will pour my Spirit upon thy seed, and my blessing upon thine offspring.`"
Thus hath the Lord preserved Zion from age to age: and I doubt not,
but am fully persuaded, that he will still bless his people and preserve Zion,
and deliver her from all her enemies.

And my dear friends, brethren and sisters,
although it be matter of sorrow to us to part with our dear friends,
especially such as have faithfully served the Lord and his people in their generation,
as it may, I hope without just occasion of offence to any,
be said of dear Thomas Ellwood; yet may we not sorrow unseasonably,
as those who sorrow without hope,
but believing that the Lord hath taken him to himself in mercy,
let us all learn resignation to his blessed will, and say with holy Job,
"`The Lord giveth, and the Lord taketh away: blessed be the name of the Lord.`"
I may farther signify unto you,
that it being my lot to be with this dear friend almost every day of his last illness,
I did observe in him, to my great comfort and satisfaction,
a quiet composed frame of mind and spirit, and resignation to the will of God.
When I came first to him, which was soon after I heard of his being taken ill,
on the 24th of the second month, I found him very much disabled by the distemper,
which was thought to be a palsy, that had seized him, especially on his right side,
so that he could not stand alone, nor help himself, but a little with his left hand;
and his speech was also very much interrupted,
insomuch that it was with great difficulty, for the most part,
that he expressed himself so as to be understood.
Some time after I came to him, there being also other friends with him,
we sat down together under a weighty exercise of spirit,
waiting upon the Lord in deep silence, with our eye to him;
it pleased the Lord eminently to appear amongst us,
and to fill our hearts with the refreshing streams of his divine love,
and to open the mouth of one of us in prayer and supplication.
The Lord was graciously pleased abundantly to replenish our spirits,
to our mutual comfort, in a living sense of divine goodness; and this our dear friend,
expressed himself in great tenderness and brokenness of spirit, on this wise,
"`I am sensibly comforted and refreshed in this visit.`"
And that afternoon, fixing his eyes upon me,
with great earnestness of spirit he expressed, as well as he could at that time,
a great concern that was upon his mind for Truth, and the friends of it,
in divers particulars; especially, in relation to our own monthly and quarterly meetings,
the writings of both which, had been under his care for more than forty years.
After this, he was much eased in his spirit, and so continued to the last,
so far as I perceived; often saying, when asked how he did?
'`I am easy, I am quiet.`'
And he was often very tender in his spirit,
expressing his resignation to the will of God, whether in life or death, saying,
'`If the Lord hath no more work for me to do, I am content and resigned to his will;
and my hearty farewell to all my brethren.`'
And at another time, nearer his end, he said to us present, in much brokenness of heart,
'`I am full of joy and peace--my spirit is filled with joy;`' or to this effect.
His speech was so weakened, that several things which he spake at times,
in a tender sense of the Lord`'s goodness, could not well be collected;
the sense of which deeply affected some of us who were with him.

My heart is sorrowfully affected at this time,
in a sense of the great loss which the church of Christ hath by his removal:
but in this I am comforted,
in a living sense of the Lord`'s mercy and goodness towards him,
in carrying him through his affliction in great patience and quietness;
under which he was sweetly refreshed by the streams of divine love,
and his cup was often made to overflow.
We, who were present, being touched with a sense thereof, were comforted;
being in a travail of spirit for him,
and did in our measures truly sympathize with him under his affliction.
And I am fully satisfied he laid down his head in peace with Lord,
and is gathered to his everlasting rest.
He departed this life the 1st of the third month, 1713,
about the second hour in the morning, in the seventy-fourth year of his age.
He received the truth in the year 1659,
and lived in fellowship with the friends of it about fifty-three years.
And I think it may be truly said of him, that as he lived so he died,
the servant of the Lord and his people, and hath left a sweet savour behind him,
and his memory is blessed with the righteous forever.
Amen.

[.signed-section-signature]
George Bowles.

[.signed-section-context-close]
Eighth month, 1713.

[.alt.centered]
=== A Testimony from the monthly meeting at Hunger-hill, the 7th of the Fourth month, 1713, concerning our dear and well-beloved friend and brother in the Truth, Thomas Ellwood, deceased.

That the dead who die in the Lord, are blessed of him, we have great assurance,
from John the divine in his writing to the seven churches; Rev. 14:13.
Where he tells them, that he heard a voice from heaven, saying, write,
Blessed are the dead which die in the Lord, from henceforth: yea, saith the Spirit,
that they may rest from their labours, and their works do follow them.
Of which number, we have no cause to doubt but this our dear friend is one;
who was eminently serviceable in the church of Christ.
He was a man to whom the Lord had given a large capacity beyond many,
and furnished him with an excellent gift;
whereby he was qualified for those services in the church,
in the performance of which he did shine as a star,
which received its lustre and brightness from the glorious Sun of Righteousness.
He was wise, but humble; condescending to the weak,
and ready to help where he saw and felt sincerity;
but sharp to that which he apprehended to be insincere and deceitful; for which cause,
he was not acceptable to hypocrites and disorderly walkers.
He was a man of a very acceptable and agreeable conversation,
as well as sober and religious, both in the church and in the world,
being of a free and affable temper and disposition, far from affectation;
but of a courteous behaviour and graceful carriage to all,
and very serviceable to and amongst his neighbours:
he was very near and dear to many of us, who were most ultimately acquainted with him,
and his memorial is sweet to us.
His services in our meetings, and in the quarterly meeting for the county of Bucks,
were very great, and of many years continuance; in which he showed great diligence,
being of a ready mind, willing to serve the church,
according to that ability which the Lord had given him;
and his heart and house were open to his friends,
and the monthly meeting was kept there more than forty years,
and remains there to this day.
Our loss is great by his removal: but in this we are satisfied,
that it is his everlasting gain; being gathered, as we have good cause to believe,
to his eternal rest.
The knowledge we had of him, and the good account which we have received of him,
in the time of his last illness, by those who were most constantly with him,
and of his quiet and peaceable departure,
do sensibly engage our hearts to acquiesce in the will of the Lord;
and therein we have peace and comfort.
He departed this life, the 1st of the third month 1713,
and was honourably buried in Friends`' burying-place at New Jordans,
in the parish of Giles-Chalfont, in the county of Bucks, the 4th day of the same month.

[.signed-section-closing]
Signed by appointment of the monthly meeting by us,

[.signed-section-signature]
George Bowles, Wm. Geimsdall, James Smith, Daniel Whakley,
Daniel Roberts, Abraham Barber, Thomas Olliffe.

[.alt.centered]
=== A Testimony from the Women`'s meeting concerning Thomas Ellwood.

A concern is upon our spirits to write somewhat
concerning our dear deceased friend and elder,
Thomas Ellwood, who was highly valued by us,
for that wisdom and counsel which were with him.
He being of a free and affable temper, ready to assist those who stood in need thereof,
encouraged many to apply to him for advice,
under the divers circumstances and various exercises which this uncertain world affords;
which we have found to be for our good, as we followed it.
He was an early comer to meetings, seldom hindered by weather,
though he lived three miles distant, when bodily weakness did not prevent,
being oft of late years, indisposed as to his health.
The monthly meeting was held at his house about forty years,
and he always looked very kind and courteous on Friends when they came there,
and took care and notice of the meanest, who came in sincerity.
He was zealous for good order, and against such, who, being in an apostatized spirit,
opposed it; and may well be numbered amongst the worthies,
whose names are upon record for their valour.
He never turned his back on such who opposed the truth; but stood his ground,
as his printed sheets on such occasions do show.
His other works manifest how great endowments God, who not only gives wisdom,
but teacheth humility, had bestowed upon him; yet we who knew him in his conversation,
are engaged to set forth how kind and condescending he was to the weakest capacity.
Many generations to come may learn how good it is to forsake all and follow Christ Jesus,
as this our friend did, as the account of his life shows.

He was greatly respected by his neighbours, for his services amongst them;
his heart and doors were open to the poor, both sick and lame, who wanted help,
and had it freely; taking care to provide things useful for such occasions, often saying,
he mattered not what cost he was at to do good.
Such lament their loss: what then may we do, who miss him in an higher station,
in his great service in the church of Christ,
but desire to be resigned to the will of the Lord;
who preserved him through all his hardships, to a dominion over false brethren,
and is now out of their reach, and of temptation too; on whose head the blessing,
asked for Joseph, rests.
As a fruitful bough his branch spread over the wall of opposition,
and his bow abode in strength;
the hands of his arms being made strong by the help of the mighty God of Jacob,
to whom be the glory for what he hath wrought in our day,
whose own works praise him forevermore.
Let the tears of sorrow that we shed, for the loss of this our deceased friend,
be remembered, and let each of us bow our spirits, in a godly care,
that we may come up according to our several capacities, to follow the Lord faithfully,
in godly zeal for his honour; and so come to lay down our heads in joy and peace,
as this our friend expressed that he did.

This eminent servant of Christ, was early convinced of the way of Truth,
wherein he continued to the finishing of his day; for the sake of which,
he soon became a sufferer; not only by imprisonment,
for worshipping God in the assemblies of his people, but also, from his father,
by whom he was made as an outcast, for no other cause,
but for his faithful testimony in taking up the
cross to the world`'s behaviour and language.
Whereupon he was invited by his much valued friend Isaac Penington, to his house,
where he abode several years, until he married.
He was a blessing in, as well as a great comfort and help to that family;
and by his wise conduct, gained much esteem, not only from the elders but the youth,
whom he instructed in learning; and though most of them are by death removed,
yet one still remains,
who from certain and experimental knowledge can commemorate his worth;
being engaged thereto, from a sense of the benefit of his good and wholesome advice.
Which friendship continued firm to the last.

His natural capacity was large, and his understanding in the things of God, very deep;
which excellent qualifications meeting in one,
rendered him useful beyond many to his country,
as well as very serviceable in the church; by both which he is,
and will be greatly missed.
But he has gone to his grave in a full age,
and gathered as a shock of corn in its season, having done his day`'s work faithfully:
so that saying may be verified in him, '`The end crowns all.`'

His sickness was sudden, which soon deprived him of the use of his limbs;
yet he retained his inward and outward senses clear;
and notwithstanding at times his pains were great,
his exemplary patience and composed resignation were
remarkably apparent to those that visited and attended him;
so that their sorrow in parting with so dear a friend,
was intermixed with comfort in beholding the
heavenly frame of mind wherewith he was adorned.

Thus after all his labours, he entered into everlasting rest,
and left many behind weeping, though not without hope,
that they shall again meet at the general assembly of saints,
where the redeemed shall sing praises to their blessed Redeemer,
whose right it is to reign forever.

We have this farther to add, namely, that our esteem of him was great,
because of that real worth that was in him,
through the operation of the mighty power of the Lord
that separated him from the love of the world:
so that he chose, with Moses, rather to suffer affliction with the people of God,
than to enjoy the pleasures of sin for a season.
It pleased the Lord to fit him with wisdom and counsel,
so that he was made able to give judgment in difficult cases,
wherein many of us particularly received benefit,
and therefore have cause to lament the loss we have by his removal.
And oh! say our souls, that the Lord would raise up many more in his room,
to the praise and honour of the good Husbandman.
And it is our desire that we, who are yet behind,
may be made able so to steer our course through this troublesome world,
that when our end comes, we may lay down our heads in peace with the Lord,
and leave a good savour behind us, as this our friend hath done.

This is written in true love and respect to the memory of our deceased friend,
as it pleased the Lord to move upon our hearts.
And being read and approved in our women`'s meeting at Hunger-hill,
the 4th of the eleventh month 1713, was subscribed in behalf of the said meeting by us,

[.signed-section-signature]
Mary Baker, Mary Wharley, Mary Larcum.

[.alt.centered]
=== Richard Vivers`' Testimony concerning Thomas Ellwood.

He was a man of great wisdom and understanding, and the Lord, the giver of it,
being pleased to visit him in his early days, made choice of him,
and by the sanctification of his Holy Spirit,
fitted and prepared him for his work and service, whereunto he was called.
Although he did not often appear as a minister,
yet in those meetings set apart for the affairs of Truth,
he often appeared in great wisdom,
having an extraordinary talent given of the Lord for that work,
more than many other brethren.
He was faithful in waiting for instruction from God, to improve the same to his glory,
and the church`'s advantage; for nothing was more desirable to him,
than to be employed in the Lord`'s service:
so it pleased the Almighty to furnish him with understanding and strength,
faithfully to do his day`'s work.
And now he hath taken him to himself, where his soul is at rest;
and although our loss be his gain, therein I with many more are greatly comforted,
for I can truly say, I loved him in the Truth,
from the first of my acquaintance with him, and so it remained to the end of his course,
being nearly forty years since we knew each other.
Whenever we conversed together, our discourse was chiefly concerning heavenly things,
and the affairs of the church.
I always thought my time well spent with him,
although opportunity would not serve for so much of it as I desired,
had it been the will of God.

He was a man true to his friend, and deliberate in the choice of his acquaintance,
to whom he showed real love and sincerity of heart.
He was one of a steady and sound judgment, as to the things of God; often desiring,
that those who came amongst us, especially children of believing parents,
might not settle down in a form of godliness, without the power,
at which door the apostasy entered; but that they might be raised up to walk in that,
wherein the saints`' fellowship doth stand, which is the light of our Lord Jesus Christ,
enlightening every man that cometh into the world.
Then the ancient testimony of Truth will be more and more raised up in their hearts,
and they being preserved of the Lord in it,
it will be maintained in its several branches, as in former days.
Blessed be the name of the Lord,
who hath a people in these latter ages of the world to whom he
hath given power to stand for his Truth whilst on earth,
and to be tender of the honour of his name; of the number of whom,
this our deceased friend and brother was; who, although dead, yet his memory liveth,
and will be preserved amongst the righteous in generations yet to come.

[.signed-section-signature]
Richard Vivers.

[.signed-section-context-close]
Banbury, 30th of Eleventh month, 1714.
